"""Deutsch: die Wörter rund um jedes README, die einzeilige Beschreibung jedes Repositorys und die Texte aller Repositorys.

Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
"""
from __future__ import annotations

UI = {
    "overview": "Überblick", "structure": "Struktur des Repositorys", "dev": "Entwicklungsumgebung", "architecture": "Architektur",
    "related": "Verwandte Projekte", "community": "Dokumentation und Community", "author": "AUTOR", "license": "LIZENZ",
    "honesty": "Ehrlichkeitsprüfung - was heute läuft", "license_text": "GPL-3.0-or-later - siehe [LICENSE](LICENSE).",
    "family": "**A.R.M.O.R.** (Autonomous Radar & Multimodal Observation Range) ist ein Perimeter-Sicherheitssystem aus unabhängigen Repositorys. Jedes hat eine eigene Version, eigene Tests und ein eigenes README; hier ist die Familie:",
    "here": "dieses Repository",
    "docs_intro": "Hier gibt es mehr zu lesen:",
    "doc_matrix": "Fähigkeitsmatrix: was belegt ist und was nicht",
    "doc_catalog": "Projektkatalog: Versionen und wie die Repositorys voneinander abhängen",
    "doc_changelog": "Änderungsverlauf dieses Repositorys",
    "doc_license": "Lizenz (GPL-3.0-or-later)",
    "contact": "Fragen, Ideen und Meldungen: electrohobby3d@gmail.com",
}

RELATED = {
    "ARMOR-COMMON": "Nachrichtenverträge, Validierer, Konformitätsvektoren und generierte Typen",
    "ARMOR-RADAR": "Feldknoten-Firmware für ESP32-S3 mit drei Radaren und eigenem Web-Panel",
    "ARMOR-SOLAR": "Protokolle für Solar-Wechselrichter und -Batterien und die Nachrichten eines Gateway-Knotens",
    "ARMOR-SERVER": "Zentraler Koordinator: Telemetrie, Alarme, Geräte, Solarmesswerte und Kameras",
    "ARMOR-STUDIO": "Web-Konsole: Kameras, Radar, Alarme, Solarenergie und 2D/3D-Standortdesigner",
    "ARMOR-ANDROID-CONTROL": "Android-Bedienclient mit Live-Radar in 2D/3D",
    "ARMOR-SERVER-AI": "Visuelle Inferenzrichtlinie, die ihre Entscheidungen erklärt und nie handelt",
    "ARMOR-VOICE-AI": "Offline-Sprachabsichten mit einer nicht fälschbaren Bestätigung",
    "ARMOR-HARDWARE": "Gehäuse, Elektronik und die Abnahmematrix am Prüfstand",
    "ARMOR-DEVOPS": "Bereitstellung, CM5-Prüfstand, Backup und TLS",
    "ARMOR-SIMULATOR": "Offline-Telemetriesimulator mit wiederholbaren Fehlern",
    "ARMOR-DOCS": "Architektur, Sicherheitsgrundlage und die Fähigkeitsmatrix",
}

TEXT = {
    "ARMOR-SIMULATOR": {
        "tagline": "Offline-Telemetriesimulator mit wiederholbaren Fehlern",
        "honest": "Die Szenarien, die Fehler, die Übermittlung an einen Server und die 26 Tests sind real. Die Geometrie ist **illustrativ**, kein Modell des echten LD2450-Radars, und nichts wurde mit echter Hardware verglichen.",
        "bullets": [
            "**Szenarien:** `patrol`, `crossing`, `two-intruders` und `empty` auf einer Eckgeometrie mit drei Sensoren, dazu ein Tag/Nacht-Lichtzyklus oder eine feste Nacht.",
            "**Wiederholbare Fehler:** ein stummer Knoten, vertauschte und doppelte Nachrichten, ein flatternder Knoten und absichtlich ungültige Nachrichten (Lux über dem Limit, unbekanntes Feld, zu viele Spuren) für Negativtests.",
            "**Deterministisch:** derselbe Seed druckt immer dieselben Zeilen; gesendet wird nur mit `--server-url` und `--ingest-token`.",
            "**Gegen den Vertrag geprüft:** `--validate` schickt jede Nachricht vor dem Ausgeben durch ARMOR-COMMON.",
            "**Sorgfältige Übermittlung:** nur ein einfacher http(s)-Ursprung wird akzeptiert; ein 4xx stoppt den Lauf, ein 5xx oder ein Netzwerkfehler wird wiederholt.",
            "**Solaranlage:** `--solar` fügt einen Wechselrichter und einen Batteriestapel aus zwei Modulen (je fünfzehn Zellen, mit Kapazitäten) über einen Zeitraffer-Tag von 240 Werten hinzu, mit einem Netzausfall am späten Tag; die Nachrichten werden gegen den Solar-Vertrag von ARMOR-COMMON geprüft und an `/api/v1/solar` geliefert.",
        ],
        "note": "Alle Optionen, Szenarien und Fehler: [Verwendung](docs/USAGE.md).",
    },
    "ARMOR-SERVER-AI": {
        "tagline": "Visuelle Inferenzrichtlinie: entscheidet und erklärt, handelt nie",
        "honest": "Die Entscheidungsschicht ist real und getestet (26 Tests). **Hier läuft noch keine Kamera, kein RTSP und kein TensorRT**: dafür braucht es den Jetson, und das ist nicht belegt.",
        "bullets": [
            "**Tag/Nacht-Profil mit Hysterese:** Schwachlicht unter 30 Lux, zurück zum Tag nur über 60 Lux und nie zweimal innerhalb von 30 s, damit die Dämmerung es nicht flattern lässt.",
            "**Erklärbare Fusion:** jede Erkennung und die Radarspuren ergeben einen Schweregrad (`ignore`, `review`, `high`) samt Gründen. Eine Person mit 80 % oder mehr **und** eine Radarspur ergeben `high`; Schwachlicht senkt nur die Prüfschwelle; eine Erkennung, die älter als 10 s ist, wird ignoriert.",
            "**Nur Empfehlungen:** eine Entscheidung trägt immer `authorizes_action = false`. Der zentrale Server authentifiziert und autorisiert jede Aktion.",
            "**Prüfsummengeprüfte Engines:** vorgebaute TensorRT-Engines werden nur akzeptiert, wenn sie vorhanden und nicht leer sind und mit einer `engines.json` ihrem SHA-256 entsprechen. Nichts wird kompiliert oder heruntergeladen.",
            "**JSONL-Worker:** nummerierte, erklärte Ergebnisse; eine fehlerhafte Zeile meldet ihre Nummer und stoppt den Strom nie.",
        ],
        "note": "Siehe die [Inferenzgrenze](docs/INFERENCE_BOUNDARY.md).",
    },
    "ARMOR-VOICE-AI": {
        "tagline": "Offline-Sprachabsichten mit einer Bestätigung, die der Aufrufer nicht fälschen kann",
        "honest": "Die Absichtsregeln, die signierte Bestätigung und das Audit sind real und getestet (20 Tests). **Eine Spracherkennungs- oder Synthese-Engine ist noch nicht Teil dieses Repositorys.**",
        "bullets": [
            "**Eine geschlossene Erlaubnisliste:** `status`, `silence`, `arm` und `disarm`, auf Englisch und Spanisch, nach Normalisierung von Akzenten, Satzzeichen und Höflichkeitsfloskeln. Alles andere oder Mehrdeutige wird nicht verstanden.",
            "**Eine vom Dienst ausgestellte Bestätigung:** `arm` und `disarm` liefern im ersten Schritt ein signiertes Token und werden nur akzeptiert, wenn ein späterer Schritt es für dieselbe Absicht innerhalb von 30 s zurückgibt. Es lässt sich nicht fälschen, umlenken, wiederverwenden oder durch ein einfaches `confirmed: true` ersetzen (wird abgelehnt).",
            "**Entscheidungen, kein Audio:** mit `--audit-file` hält jede Entscheidung Absicht, Ergebnis und einen SHA-256 des Transkripts fest, nie Audio oder die rohen Wörter.",
            "**Nur Empfehlungen:** ein akzeptierter Befehl wird an ARMOR-SERVER weitergegeben, der ihn weiterhin authentifiziert und autorisiert.",
        ],
        "note": "Siehe die [Sprachsicherheit](docs/SAFETY.md).",
    },
    "ARMOR-SOLAR": {
        "tagline": "Solar-Gateway-Knoten: liest Wechselrichter und Batterien über bis zu zehn serielle Ports (ESP32-S3-Firmware, sein Web-Panel und die Protokollbibliothek)",
        "honest": "**Reifegrad: Scaffolding.** Die Firmware baut im ESP-IDF-5.4.2-Container, ihr Kern (die Einstellungen, der Austausch mit jeder Geräteart, die Arithmetik des emulierten UART: 697 Prüfungen) ist am Rechner mit Stellvertreter-Geräten getestet, die Nachrichten, die sie erzeugt, akzeptiert ARMOR-COMMON, und das Panel wurde in einem Browser gegen einen Stellvertreter-Knoten ausprobiert. **Sie lief nie auf einer Platine, und es wurde kein Wechselrichter und keine Batterie angeschlossen**: das WLAN, das Panel mit TLS, das Update, die Hardware- und emulierten UARTs und die Formate der Protokolle (aus öffentlichen Dokumenten und aus dem Gedächtnis geschrieben) sind unerprobt. Die ANT-BMS-Frames in den Tests wurden von anderen an deren eigenen Geräten aufgezeichnet: dieses Projekt hat selbst noch keines gelesen.",
        "bullets": [
            "**Zwei Platinen, eine Firmware:** ein ESP32-S3-WROOM-1 N16R8 per WLAN (Standard) und die Waveshare ESP32-S3-ETH am Ethernet-Kabel (DHCP oder feste Adresse; ihr eigenes WLAN bleibt, um sie vom Handy aus zu erreichen). Das Image wird beim Bauen gewählt (`tools/build_node.sh generic s3-wifi` oder `generic s3-eth`); Pin-Tabelle, Standard-Pins der Ports und Zugangsweg folgen der Platine, und ein Image gilt nur für seine Platine. Beide bauen und sind am Rechner getestet; keine lief je auf einer Platine.",
            "**Die Firmware des Knotens** (ESP32-S3-WROOM-1 N16R8 per WLAN oder Waveshare ESP32-S3-ETH am Kabel): zehn serielle Ports, drei Hardware-UARTs und sieben emulierte (bis 19200 Baud), jeder unabhängig und jeder liest einen Wechselrichter, eine Batterie oder einen Rohmonitor, sodass ein Knoten nur Wechselrichter, nur Batterien oder eine Mischung lesen kann.",
            "**Das Web-Panel des Knotens,** auch das der Radarknoten: Einrichtung mit einem Code, der auf der USB-Konsole erscheint, Anmeldung und Benutzer, WLAN (Station und Access Point), Broker, Update per Funk mit Rollback, Protokoll, HTTPS und die Seiten der Ports (mit dem, was jeder hört, für noch nicht dekodierte Protokolle) und der Messwerte, in sieben Sprachen.",
            "**Voltronic- / MPP-Solar-Wechselrichter** (Axpert, PIP, InfiniSolar und Klone), RS232 mit 2400 Baud: die Rahmen und ihre CRC sowie die Messwerte `QPIGS` (Netz, Ausgang, Batterie, PV, Statusbits), `QMOD` (Modus), `QPIWS` (Warnungen und Störungen mit Namen) und `QPIRI` (Nennwerte). Nur lesende Befehle lassen sich bauen: eine Einstellung ändert, wie das Haus versorgt wird. Drei Dialekte, am Port gewählt oder von ihm gefunden (*auto*): PI30, REVO (ein anderes `QPIGS`, Antworten mit Prüfsumme) und PI18 (`^P005GS`: InfiniSolar V, LV5048, SunGoldPower), nur lesend.",
            "**Pylontech-Batterien** (US2000, US3000, US5000): die `pwr`-Tabelle der Konsole (Spannung, Strom, Temperaturen und Ladezustand jedes Moduls), `bat <n>` (Spannung und Temperatur jeder Zelle) und `info <n>` (Modell, Rest- und Gesamtkapazität, Zyklen), zusammengefasst als ein Stapel mit Gesamtkapazität und -energie, und der RS485-Rahmen mit seinen zwei Prüfungen. Die Formate sind aus dem Gedächtnis der öffentlichen Konsole geschrieben und können sich je nach Firmware unterscheiden. Die Spalten werden über die Namen der Kopfzeile gefunden (auch das Format der US5000 V2.3 mit Id-Spalten, MosTempr und SysAlarm.St), die Restladung und das Balancing kommen aus `bat`, Modell, Nennkapazität und Zyklen aus `info` und `stat`, die einmal abgefragt und eine halbe Stunde behalten werden.",
            "**Die Nachrichten des Knotens** (`armor/solar/<Knoten>/<Gerät>/state`, eine je Wechselrichter oder Batteriestapel), in ARMOR-COMMON mit Schemas und Konformitätsvektoren definiert; was die Ports erzeugen, wird dagegen geprüft.",
            "**ANT-BMS-Batterien** (die schwarzen Platinen selbstgebauter Akkus, 7S bis 32S), 3,3-V-UART mit 19200 Baud: beide Protokolle seiner Firmware (der Knoten fragt im einen und dann im anderen und bleibt bei dem, das antwortet), mit Zellen, Temperaturen, Ladezustand, Strom, Kapazitäten sowie den Zuständen der MOSFETs und des Balancers, geprüft an Frames, die an vier echten Modellen aufgezeichnet wurden. Nur Lesen: seine Schreibbefehle können eine Batterie unter Last trennen. Eine Schaltfläche auf der Port-Seite liest außerdem Modell, Version und 56 Schutz- und Balancing-Einstellungen des BMS (neueres Protokoll), nur lesend.",
            "**Noch nicht:** die Bluetooth-Verbindung des ANT-BMS (der Knoten nutzt das Kabel, das stabilere von beiden) und ein Lauf auf einer echten Platine mit echten Geräten.",
        ],
        "note": "Siehe die [Firmware-Anleitung](docs/NODE_FIRMWARE.md) (die Platine, die Ports, der erste Start und die Prüfliste am Prüfstand) und die [Verdrahtungshinweise](docs/NODE_HARDWARE.md).",
    },
    "ARMOR-RADAR": {
        "tagline": "Feldknoten-Firmware (Waveshare ESP32-S3-ETH, drei Radare oder Präsenzsensoren, Ethernet und WLAN) mit eigenem Web-Panel und ihrem am Rechner getesteten Kern",
        "honest": "**Reifegrad: Scaffolding.** Der hardwareunabhängige Kern (859 Prüfungen: die Dekoder des LD2450, des LD2461 und vier Präsenzsensoren, der Befehlskanal des LD2450, die Einstellungen und ihre Prüfungen, die Pin-Tabelle, Benutzer und Sitzungen, die Logik der zugeordneten Pins, der Netzplan und der Nachrichten-Serialisierer, dessen Ausgabe ARMOR-COMMON akzeptiert) ist am Rechner getestet, das **Web-Panel** wurde in einem echten Browser gegen einen Stellvertreter-Knoten ausprobiert, und das **Firmware-Image baut** im ESP-IDF-5.4.2-Container. **Es lief nie auf einer Platine**: kein Rahmen wurde von einem echten Modul aufgenommen, der Code für Ethernet, WLAN-Brücke, Lichtsensor und Update ist unerprobt, der Befehlskanal der Radare ist weder am Herstellerdokument noch an einem Modul geprüft, das HTTPS-Zertifikat des Panels erzeugt der Knoten selbst und es ist in einem echten Browser unerprobt, und die Dekoder für LD2461 und Präsenzsensoren entsprechen nur den Beispielen ihrer Handbücher, ohne echtes Modul.",
        "bullets": [
            "**Zwei Platinen, eine Firmware:** die Waveshare ESP32-S3-ETH (Ethernet, Standard) und ein ESP32-S3-WROOM-1 N16R8 ohne Ethernet (nur WLAN: die Einrichtung fragt nach dem WLAN zum Beitreten, und der Knoten behält immer sein eigenes Netz). Das Image wird beim Bauen gewählt (`tools/build_node.sh generic s3-eth` oder `generic s3-wifi`); Pin-Tabelle und Zugangsweg folgen der Platine, das Panel blendet aus, was die Platine nicht hat, und ein Image gilt nur für seine Platine. Beide bauen und sind am Rechner getestet; keine lief je auf einer Platine.",
            "**Zwei Knoten mit 270 Grad:** jedes Waveshare ESP32-S3-ETH liest bis zu drei LD2450-Radare an seinen drei UARTs, im Abstand von 75 Grad montiert, über kabelgebundenes Ethernet (W5500) mit DHCP oder fester Adresse, gespeist per PoE oder USB. Studios *Add a 270° node* legt die drei Radare bereits dem Knoten zugeordnet an.",
            "**Ein Web-Panel auf jedem Knoten,** im Aussehen von Studio und in sieben Sprachen, in die Firmware eingebettet: Übersicht, Netzwerk, WLAN, Broker, Radare, Pins, Benutzer, Firmware-Update und Protokoll. Ein Knoten ohne Benutzer öffnet das WLAN `ARMOR-SETUP-xxxxxx` und legt mit einem Einrichtungscode seinen ersten Administrator an; Passwörter sind gesalzenes PBKDF2, Sitzungen zufällige Token, und jede Einstellung liegt im Flash des Knotens, sodass ein Image alle Knoten bedient und kein Passwort einkompiliert ist ([das Panel](docs/NODE_PANEL.md)).",
            "**Ein WLAN aus vielen Knoten:** jeder Knoten kann einen an seinen Ethernet-Port angebundenen Access Point anbieten; mit gleichem Namen und Passwort und dem Kanal auf automatisch (1, 6 oder 11 nach MAC) sehen Telefone und WLAN-Sensoren ein Netz mit einem DHCP-Server. Es ist kein Funk-Mesh: jeder Knoten behält sein Kabel. Ein Knoten kann stattdessen dem WLAN eines Routers beitreten (mit Netzwerksuche), und einer ohne Kabel lässt sich per **Bluetooth** über die Android-App konfigurieren.",
            "**Pins für den Server:** jeder freie Pin wird zu einem Eingang, einem Ausgang (mit sicherem Zustand bei Verlust des Brokers), PWM oder einer analogen Messung und erscheint als Gerät des Servers, sodass ein Relais oder ein Kontakt keine neue Firmware braucht. Die reservierten Pins der Platine werden nie angeboten.",
            "**Over-the-Air-Updates mit Rollback** aus dem Panel (zwei Slots im 16-MB-Flash) und ein **Link aus Studio** zum Panel jedes Knotens, über die Adresse, die der Knoten veröffentlicht.",
            "**Das Panel über HTTPS:** der Knoten erzeugt sein eigenes Zertifikat (selbstsigniert, im Flash gehalten) und bedient das Panel auf Port 443 zusätzlich zu 80 oder nur auf 443; das Sitzungs-Cookie ist als Secure markiert und der Fingerabdruck des Zertifikats wird zum Vergleich mit der Browserwarnung angezeigt. **Stabile Spur-Identitäten:** die Ziele jedes Rahmens werden den zuvor verfolgten zugeordnet, sodass eine Person dieselbe Spur-ID behält, ein verlorener Rahmen nicht flackert und die Positionen leicht geglättet werden.",
            "**Sechs Sensormodelle, eines je Port:** ein Port trägt einen LD2450 oder LD2461 (Tracker, die den Perimeter speisen, mit dem eigenen Feld des Modells in Studio) oder einen Präsenzsensor (LD2410, LD2412, LD2410S, MR24HPC1), der zum Gerät des Servers wird und Anwesenheit und Entfernung veröffentlicht. Im Panel gewählt; was jeder ist, sein Protokoll und was nicht geprüft wurde, steht in `docs/SENSORS.md`.",
            "**LD2450-Dekoder, Zustand und Konfiguration:** ein neu synchronisierender Rahmenfinder findet Rahmen in einem verrauschten Strom; jeder 30-Byte-Rahmen liefert bis zu drei Ziele, die zu Vertragsspuren werden; Konsole und Panel sagen je Radar, ob es meldet, schweigt oder Unsinn sendet. Das Panel kann auch die Version des Moduls lesen, ein oder drei Ziele wählen und Erkennungszonen setzen (ein an einem Modul ungeprüftes Protokoll).",
            "**Umgebungslicht und vertragsgenaue Nachrichten:** der VEML7700 mit automatischem Bereich; Telemetrie-, Zustands- und Informations-JSON folgt den veröffentlichten Schemas und weigert sich, Ungültiges zu schreiben, mit Wanduhr-Zeitstempeln (SNTP) und einem MQTT-Last-Will. Telemetrie wird zurückgehalten, solange kein Radar meldet, nie eine leere „Entwarnung“.",
            "**Ein Image für jede Platine, wie ein Netzwerkprodukt:** die Firmware ist dieselbe und die MAC unterscheidet die Platinen (`armor-` und sechs Ziffern bis zur Benennung); `adopt_node.py` gibt einem frisch geflashten Knoten über das Netzwerk seinen Administrator, seine Broker-Identität und die gemeinsamen Einstellungen der Flotte, mit einem aus seiner MAC berechneten Einrichtungscode: 5 Knoten oder 27 sind dieselbe Arbeit. **Werkzeuge am Prüfstand:** Flashen per USB-C, ein Stellvertreter-Knoten zum Arbeiten am Panel und ein Konverter von einem Protokoll roher Rahmen zu einem Testfixture ([Inbetriebnahme am Prüfstand](docs/BENCH_BRINGUP.md)).",
        ],
        "note": "Die Rechnertests brauchen einen C++17-Compiler (Linux, WSL, MSYS2). Siehe die [Inbetriebnahme am Prüfstand](docs/BENCH_BRINGUP.md), das [Panel](docs/NODE_PANEL.md) und die [Hardwaregrenze](docs/HARDWARE_BOUNDARY.md).",
    },
    "ARMOR-ANDROID-CONTROL": {
        "tagline": "Mobiler Bedienclient für ARMOR-SERVER",
        "honest": "Die Regeln für Adresssicherheit und Alarmentscheidung haben Unit-Tests (55) und die App baut. Sie wurde **nicht auf einem Telefon gegen den Server ausgeführt**, daher sind der Berechtigungsablauf der Benachrichtigungen und der Hintergrunddienst ungeprüft. Scharfschalten, Alarme und Geräte folgen den Routen des Servers, wurden aber auf keinem echten Telefon ausprobiert.",
        "bullets": [
            "**Anmeldung mit dem Login des Servers:** IP, Port, Benutzer und Passwort; das Passwort erzeugt eine HttpOnly-Sitzung und wird nie auf dem Telefon gespeichert.",
            "**Kameramonitor:** 1 bis 16 Kacheln, eine maximierte Ansicht, MJPEG live mit erhaltenem Bildverhältnis, ein begrenztes PTZ-Pad, Schnappschüsse und Aufnahmen.",
            "**Scharf- und Unscharfschalten** nach einer Bestätigung; **Alarme** zum Quittieren, mit einem Badge für wartende; **Geräte** (Rauch, Gas, Wasser, Tür, Fenster, Bewegung, Klima, Steckdosen, Lichter, Sirenen, Schlösser) mit ihrem Zustand und Ein / Aus / Umschalten.",
            "**Live-Radar in 2D und 3D:** der Radar-Tab zeichnet den Standort, wie er in Studio entworfen wurde (Gelände, Gebäude, Bäume, Pfosten, die Felder der Radare und Kameras) und die Personen, die die Radare sich bewegen sehen, alle anderthalb Sekunden aktualisiert; die 3D-Ansicht lässt sich ziehen, zoomen und drehen. Die Platzierung folgt den Regeln von Studio, hat aber nie ein echtes Radar gezeigt.",
            "**Solar:** ein Eintrag in *Más* (und eine Kachel im Status) zeigt die Summen (Sonne, Verbrauch, Batterien mit Ladung und Fluss, ob das Netz da ist) und jeden Wechselrichter und jede Batterie, die der Server meldet: ihre Werte, auf Wunsch die Zellen einer Batterie mit markierter höchster und niedrigster, die Geräte, die noch auf Daten warten, und eine Markierung bei Beispielwerten oder einem stummen Gerät. Alle fünf Sekunden aktualisiert, solange sie offen ist; gegen die Antwortformen des Servers getestet und in einem Emulator gegen einen lokalen Server mit Beispielwerten ausprobiert, nie mit echten Geräten. Solar-Alarme (Wechselrichterfehler, schwache oder sich schützende Batterie, verstummtes Gerät) wecken das Telefon wie ein Geräte-Alarm.",
            "**Einen Feldknoten per Bluetooth einrichten** (vom Anmeldebildschirm oder *Más > Configurar un nodo*): findet Knoten, die `ARMOR-xxxxxx` senden, legt den Administrator eines neuen an oder meldet sich an, sucht WLAN-Netze und setzt den Namen des Knotens, das WLAN eines Routers oder eine feste Adresse und den Broker, für Knoten ohne Ethernet-Kabel. Gebaut und per Unit-Test geprüft, nie gegen einen Knoten oder ein Telefon ausgeführt.",
            "**Beweisbibliothek,** Zustand von Perimeter und Knoten und ein **Verlauf** jeder Warnung, jedes Knotens, jeder Kamera, jedes Geräts, jedes Alarms und jedes Moduswechsels.",
            "**Alarmbenachrichtigungen** für einen Knoten, der HIGH erreicht, eine Kamera, die nicht mehr antwortet, einen Geräte-Alarm (Rauch, Gas, Wasser, Panik jederzeit; ein Tür-, Fenster- oder Bewegungssensor bei Scharfschaltung) und, scharf, einen Knoten, der offline geht; eine optionale Hintergrundüberwachung nutzt die aktuelle Sitzung und meldet, wenn sie endet.",
            "**Vorsicht mit dem Passwort:** einfaches HTTP ist nur zu einem privaten LAN- oder Loopback-IPv4-*Literal* erlaubt. Ein Hostname, der nur wie eine private Adresse beginnt (`10.attacker.example`), oder eine Adresse mit führender Null (manche Resolver lesen `010.0.0.1` als die öffentliche `8.0.0.1`) wird abgelehnt.",
            "**Ein Aussehen aus Symbolen:** fast schwarze Flächen, ein Cyan-Akzent, Bernstein für Aufmerksamkeit, große Symbole mit wenigen Worten, eine untere Leiste, eine Info-Seite und eine Abmelde-Schaltfläche.",
        ],
        "note": "Das Debug-APK ist nicht für die Verteilung signiert. Siehe die [Client-Grenze](docs/CLIENT_BOUNDARY.md).",
    },
    "ARMOR-HARDWARE": {
        "tagline": "Gehäuse, Elektronik und die Abnahmematrix am Prüfstand",
        "honest": "Das Gehäuse ist ein **druckbarer mechanischer Ausgangspunkt, keine IP-, HF- oder Thermik-Zertifizierung.** Nichts wurde an einem Prototyp gemessen; jede Zeile der [Abnahmematrix am Prüfstand](docs/BENCH_ACCEPTANCE.md) ist *nicht getestet*.",
        "bullets": [
            "**Das echte Design ist `CAD/CARCASA_SENSORES.scad`** (mit STL-, 3MF- und AMF-Exporten): eine 90-Grad-Eckbasis mit Blende, Dach und Boden, Halte-Stufen, einer verschiebbaren 2-mm-Frontabdeckung und Seitenklappen, alles über benannte Parameter gesteuert. `scad/node_enclosure.scad` ist nur eine Platzhalterbox.",
            "**Reservierte Volumen** für drei Radarmodule, die Platine ESP32-S3-ETH-PoE, das Sensorfenster, eine Kabelverschraubung, die PoE-Magnetics und die PTC-Heizung. Kein metallisches, leitfähiges oder kohlenstoffgefülltes Material vor einer 24-GHz-Öffnung ohne gemessene Dämpfung.",
            "**Abnahmematrix am Prüfstand:** die Prüfungen für Funk, Umgebung, Strom, Netz und Kamera, jeweils mit Methode und vorgeschlagenem Bestehenskriterium, und eine auszufüllende Kamera-Kompatibilitätstabelle.",
            "Vor der Fertigung genaue Platinenumrisse, Steckverbinder, Schraubenpositionen, Antennen-Freihaltezonen, den Wärmepfad und das Schutzziel festhalten ([Entwurfseingaben](docs/DESIGN_INPUTS.md)).",
        ],
        "note": "Siehe die [Validierungsgrenze](docs/VALIDATION.md). Die vorgesehene Hardwarelizenz ist CERN-OHL-S-2.0; den vollen Text vor der Veröffentlichung der Entwürfe hinzufügen.",
    },
    "ARMOR-DEVOPS": {
        "tagline": "Bereitstellungstopologie und der isolierte CM5-Prüfstand",
        "honest": "Der Installer des CM5-Prüfstands wurde auf einer echten CM5 ausgeführt, die andere Software hostet und gesund blieb. Die Docker-Compose-Topologie und ihr optionales TLS-Profil wurden mit der Docker Engine in WSL wirklich gebaut und ausgeführt (`scripts/test_compose.sh`, 12 Prüfungen, die drei Fehler fanden und behoben), aber **nicht auf dem Jetson**. Die Backup- und Wiederherstellungsskripte haben einen bestandenen Rundlauftest.",
        "bullets": [
            "**Eine Host-Firewall für den zentralen Rechner** (`scripts/firewall_core.sh`): der Port des Brokers nur aus dem Feldnetz, die Ports von Server und Studio nur aus dem Netz der Clients (wenn angegeben), in einer eigenen Tabelle, die nichts anderes erwähnt und den Rest annimmt; `apply --rollback-after` entfernt die Regeln wieder, wenn Sie sie nicht bestätigen, ein Fehler sperrt Sie also nicht aus. Regeln und Ablehnungen sind getestet (36 Prüfungen, nichts wird geladen); sie wurde noch auf keinem Rechner geladen, und die VLANs selbst sind weiter ein Entwurf für Router und Switch.",
            "**CM5-Prüfstand:** `scripts/deploy_cm5.sh` baut in einer sauberen Kopie, sendet ein Archiv und führt `scripts/install_cm5.sh` aus, das einen eigenen Benutzer, ein eigenes Verzeichnis und zwei systemd-Units auf eigenen Ports anlegt (drei mit `--with-mqtt`: das eigene Mosquitto von A.R.M.O.R. auf Port 18883, auf einer echten CM5 geprüft), mit Ressourcenlimits, und nie ein anderes Projekt anfasst ([Details](docs/CM5_TEST_BENCH.md)).",
            "**Compose-Topologie:** ein nicht anonymer Mosquitto-Broker mit einer Identität je Knoten, der Server und Studio hinter einem nginx, der `/api/` weiterreicht; nur Studio wird veröffentlicht, auf Loopback. Gehärtete Container, ein internes Kernnetz und benannte Volumes für den Zustand.",
            "**Geräte und Messwerte am Broker des Prüfstands:** der Server darf `armor/device/#` hören und ansteuern und `armor/node/+/info` sowie `armor/solar/#` lesen; `scripts/mqtt_identity.sh add device NAME` gibt einem Gerät eigene Topics und `add bridge NAME` einer Zigbee2MQTT- oder Shelly-Brücke alle.",
            "**Geheimnisse:** `scripts/generate_secrets.sh` erzeugt zufällige Geheimnisse und druckt keines; `scripts/check-required-env.sh` lehnt fehlende, Platzhalter-, kurze oder wiederholte Werte ab.",
            "**Backup und Wiederherstellung:** `scripts/backup_data.sh` erstellt ein AES-256-verschlüsseltes, verifiziertes und mit Prüfsumme versehenes Archiv der Serverdaten (Beweise nur auf Wunsch); `scripts/restore_data.sh` listet es auf oder stellt es wieder her, ohne je vorhandene Daten zu überschreiben. Der Kameraschlüssel ist absichtlich **nicht** im Archiv.",
            "**TLS:** ein optionales Compose-Profil `tls` stellt Caddy mit eigener lokaler Zertifizierungsstelle vor Studio ([Details](docs/BACKUP_AND_TLS.md)).",
        ],
        "note": "Siehe die [Bereitstellungsgrenze](docs/DEPLOYMENT_BOUNDARY.md).",
    },
    "ARMOR-SERVER": {
        "tagline": "Zentraler Sicherheitskoordinator: Telemetrie-Eingang, Alarme, Geräte, Solarmesswerte und Kamera-Gateway",
        "honest": "Jede Route, Sitzung, Verschlüsselung und Beweisregel unten ist real und durch Tests abgedeckt (`npm test`, 161 Tests, darunter eine vollständige HTTP-Integrationssuite gegen einen isolierten Server). Er lief gegen einen echten MQTT-Broker auf der CM5 (mit Skripten, nicht mit Feldknoten-Firmware) und hat Live-Video gestreamt, einen Schnappschuss gespeichert und von fünf echten IP-Kameras über FFmpeg aufgezeichnet. **Noch nicht belegt:** ONVIF mit einer echten ONVIF-Kamera, PTZ auf jeder Kamera-Firmware (es funktioniert an der Hi3510-Einheit), jede Jetson-Hardware und die Solar-Routen mit einem echten Gateway-Knoten (sie sind mit erzeugten Messwerten getestet).",
        "intro": "**ARMOR-SERVER** ist das vertrauenswürdige Zentrum von A.R.M.O.R. Feldknoten veröffentlichen Radar-, Licht- und Zustandsbeobachtungen; dieser Dienst validiert sie, hält den letzten bekannten Zustand jedes Knotens und stellt ihn der Studio-Konsole und dem Android-Client bereit. Er besitzt auch alles, was eine Kamera berührt, sodass **kein Browser und kein Telefon je ein Kamerapasswort oder eine RTSP-Adresse hält**.",
        "bullets": [
            "**Validierter Eingang:** HTTP- und MQTT-Beobachtungen werden an der Grenze geprüft (Kennung, Zeitstempel, Lux-Bereich, höchstens 15 Spuren), bevor sie die Zustandsprojektion erreichen.",
            "**Ehrlicher Knotenzustand:** ein Knoten, der verstummt, wird nach einem einstellbaren Fenster als *veraltet* und *offline* angezeigt, nie als online mit alten Daten. Unscharfschalten löscht eine hohe Warnung sofort.",
            "**Kamera-Gateway:** verschlüsselter Kamera-Tresor, ONVIF- / Hi3510- / PSIA-PTZ, RTSP-Pfadsuche, ein geteiltes FFmpeg-Relay je Kamera, Schnappschüsse und MP4-Aufnahme sowie ein Wächter, der eine Kamera, die nicht mehr antwortet, zu einem Ereignis und, scharf, zu einem Alarm macht.",
            "**Beweisbibliothek:** Aufbewahrung nach Alter und Größe, die ältesten zuerst, **geschützte Beweise**, die nie bereinigt werden, und ein SHA-256 für die Beweiskette. Eine Audit-Zeile je sicherheitsrelevanter Aktion, ohne Zugangsdaten.",
            "**Zustand, der überlebt:** der Sicherheitsmodus und die letzte Beobachtung jedes Knotens werden nach einem Neustart wiederhergestellt (ein Neustart schaltet den Perimeter nie stillschweigend unscharf). Jede Änderung von Warnstufe, Knotenzustand und Modus steht in einem Ereignisverlauf.",
            "**Alarmausgabe:** hohe Warnungen und, scharf, stumme oder Offline-Knoten gehen an MQTT `armor/server/alert` und einen optionalen HMAC-signierten Webhook; die Verweilzeit vor HIGH und Ignorierzonen stellt man in Studio ein.",
            "**Benutzer:** Namen und Passwörter (scrypt-Hashes), eine Rolle `admin`, die Benutzer verwaltet, und eine Rolle `operator`, die bedient; ein geändertes Passwort oder eine geänderte Rolle beendet die anderen Sitzungen dieses Benutzers.",
            "**Geräte, Alarme und Automatisierungen:** Rauch-, Gas-, Wasser-, Tür-, Fenster-, Bewegungs-, Klima-, Steckdosen-, Licht-, Sirenen- und Schlossgeräte über MQTT oder authentifizierten Push, mit normalisiertem Zustand, Verfügbarkeit und Befehlen; Alarme mit Lebenszyklus ausgelöst / quittiert / gelöscht; Regeln, die bei einem Ereignis Geräte schalten; Scharf- und Unscharfschalten aus einer angemeldeten Sitzung; und der Standortentwurf, für alle Clients auf dem Server gehalten.",
            "**Solarmesswerte:** Wechselrichter und Batteriestapel (mit jeder Zelle und den Kapazitäten) kommen per HTTP oder MQTT, werden vom gemeinsamen Vertrag validiert, mit Verlauf (ein Wert alle 30 s über einen Tag) und Summen gehalten, nach zwei Minuten als veraltet markiert und lösen vier Alarme aus (Wechselrichterstörung, Batterie schwach, Batteriealarm, Gerät stumm).",
        ],
        "sections": [
            {"title": "Sicherheitsmodell", "bullets": [
                "Vier getrennte Geheimnisse: **Ingest** (Telemetrie, Zustand und Solarmesswerte senden), **Control** (Scharf-/Unscharfschalten, Ereignisse), **Operator** (Automatisierung) und der **Studio-Login**; jedes wird in konstanter Zeit verglichen und keines ersetzt ein anderes.",
                "Jede Route, die konfiguriert, bewegt, aufnimmt, aufzeichnet, schützt oder löscht, braucht einen Operator. Live-Video braucht einen Operator oder ein kurzlebiges, an eine Kamera gebundenes Stream-Ticket.",
                "Kamerapasswörter liegen nur in `data/cameras.json`, AES-256-GCM-verschlüsselt, und keine API gibt sie zurück; ONVIF-Adressen müssen auf dem Host der Kamera bleiben, Weiterleitungen werden abgelehnt.",
                "Studio-Sitzungen sind 8 Stunden lang HttpOnly und SameSite=Strict, die Anmeldung ist ratenbegrenzt und Fehler tragen nie einen Stacktrace.",
                "Der Server lauscht auf 127.0.0.1, außer `ARMOR_HOST` wird absichtlich gesetzt; dann wird ein Studio-Passwort unter 12 Zeichen abgelehnt.",
            ]},
            {"title": "API", "bullets": [
                "Öffentlich: `GET /healthz`. Für einen Operator: Status, Informationen, Kameras, Medien, Verlauf, Regeln, Geräte, Alarme, Automatisierungen, der Standortentwurf und `GET /api/v1/solar` mit Verlauf.",
                "Für Feldknoten und Gateways: `POST /api/v1/telemetry`, `/health` und `/solar` mit dem Ingest-Token sowie die MQTT-Topics `armor/node/#` und `armor/solar/#`. Ereignisse erreichen die Konsolen über den WebSocket `/api/v1/events`.",
                "Jede Route, ihre Zugriffsregel und ihr Schema stehen in der OpenAPI-Datei von [ARMOR-COMMON](../ARMOR-COMMON), und ein Test prüft, dass keine Route fehlt.",
            ]},
            {"title": "Konfiguration", "bullets": [
                "`.env.example` nach `.env` kopieren (von Git ignoriert) oder `run.bat` / `run.sh` beim ersten Lauf zufällige Geheimnisse erzeugen lassen.",
                "Pflicht: `ARMOR_INGEST_TOKEN` und `ARMOR_CONTROL_TOKEN` (24 Zeichen oder mehr, alle verschieden) und `ARMOR_STUDIO_USERNAME` / `ARMOR_STUDIO_PASSWORD` (der erste Administrator).",
                "Üblich: `ARMOR_HOST` / `ARMOR_PORT`, `ARMOR_DATA_DIR`, `ARMOR_FFMPEG_PATH` (Live-Video und Aufnahme), `ARMOR_MQTT_URL`, `ARMOR_STUDIO_ORIGIN`, `ARMOR_NODE_STALE_AFTER_S`, `ARMOR_CAMERA_CHECK_S`, `ARMOR_ALERT_DWELL_MS`, `ARMOR_ALERT_WEBHOOK_URL` und `ARMOR_COOKIE_SECURE` (hinter TLS auf `1`).",
            ]},
        ],
        "note": "Zur Installation auf dem CM5-Prüfstand (isoliert von jedem anderen Projekt, eigener Benutzer, eigene Ports) siehe [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-STUDIO": {
        "tagline": "Betriebs- und Entwurfskonsole: Kameras, Radar, Alarme, Solarenergie, Beweise und Standortplan",
        "honest": "Studio spricht mit [ARMOR-SERVER](../ARMOR-SERVER) und ist durch 176 Unit-Tests abgedeckt (Einstellungen lesen, Kameras zusammenführen, die Arithmetik der Solar-Diagramme, jedes Menü in den sieben Sprachen dargestellt, der statische Host). **Nicht belegt** sind Live-Video und PTZ mit jeder echten Kamera, die Solarmenüs mit einem echten Wechselrichter oder einer echten Batterie und eine formale Barrierefreiheits- oder Usability-Prüfung. Solange der Server nicht erreichbar ist, zeigt Studio Demodaten und sagt das in der oberen Leiste.",
        "intro": "**ARMOR-STUDIO** ist die Konsole des Bedieners. Sie hält nie ein Kamerapasswort, eine RTSP-Adresse oder ein Token: sie meldet sich mit Benutzername und Passwort am Server an, erhält eine **HttpOnly**-Sitzung von 8 Stunden, und alles Privilegierte läuft über diese Sitzung.",
        "bullets": [
            "**Kameramonitor:** 1, 2, 4, 6, 8, 9, 12 oder 16 Kacheln, die in ihren Rahmen passen (16:9, die ganze Matrix sichtbar, ohne Beschnitt), eine maximierte Ansicht mit begrenztem PTZ-Pad, Schnappschuss und MP4-Aufnahme; eine **Aufnahmebibliothek** zum Filtern, Vorschauen, Abspielen, Schützen und Löschen von Beweisen.",
            "**Alarme, Geräte und Automatisierungen:** was jetzt einen Menschen braucht, mit Quittieren und dem geschlossenen Protokoll; Rauch-, Gas-, Wasser-, Tür-, Fenster-, Bewegungs-, Klima-, Steckdosen-, Licht-, Sirenen- und Schlossgeräte über WLAN, Zigbee, Bluetooth oder Kabel (Vorlagen für Zigbee2MQTT, Tasmota und Shelly); Regeln, die bei einem Ereignis Geräte schalten; eine große Scharf-/Unscharf-Schaltfläche.",
            "**Solarenergie:** das Menü *Wechselrichter* zeichnet das Haus als animierten Energiefluss (Module, Netz, Wechselrichter, Batterie und Last, mit Strichen, die bei mehr Leistung schneller laufen), Anzeigen, Messwerte, Warnungen in Worten und Verlaufsdiagramme; das Menü *Batterien* zeigt jeden Stapel mit einem Flüssigkeitspegel, seine **Kapazitäten** (Rest und gesamt, Ah und kWh, Zyklen, Modell), jedes Modul und **jede Zelle** als Balken mit Spannung und Spreizung in Millivolt sowie Diagramme für Ladung, Spannung, Strom, Zellbereich und Temperatur.",
            "**Übersicht und System:** der Zustand des Perimeters, eine Kachel je Teil, eine Live-Karte des Entwurfs mit jedem Gerät und eine Systemseite mit dem Audit-Protokoll für einen Administrator.",
            "**Radar:** eine Live-Karte, aus deinem Standortentwurf gezeichnet (Gelände, Gebäude, Kameras, Radare und ihre Abdeckung), mit den Zielen, die jedes Radar meldet, ihrem jüngsten Weg und den Ignorierzonen; Live-Knotenzustand, stumme Knoten als *veraltet*; das eigene Panel jedes Knotens ist einen Klick entfernt.",
            "**Standortdesigner:** das Gelände zeichnen (Rechteck oder beliebige Form, mit eingetippten Längen), Gebäude mit mehreren Stockwerken und fünf Dacharten platzieren, Türen und Fenster in jedem Stockwerk und jeder Höhe, Lampen, Schornsteine, Solarmodule, Antennen, Pfeiler, Masten, Straßen und Wege, dann Kameras und Radare, wo man will; ein 2D-Plan im CAD-Stil und eine 3D-Ansicht, die man umkreisen, stockwerksweise schneiden und bearbeiten kann; Rückgängig und Wiederholen.",
            "**Konfiguration:** Serveradresse, Kameras (ONVIF/RTSP), Suche, Benutzer (das eigene Konto und für einen Administrator die Liste von Benutzern, Rollen und Passwörtern), Thema und Sprache; ein portabler Standortexport **ohne Zugangsdaten**.",
            "**Sieben Sprachen** (Englisch, Spanisch, Deutsch, Französisch, Italienisch, Japanisch, Chinesisch) und elf Themen, das Standardthema heißt *Armor*.",
            "**Deklariere dein Gerät:** in den Menüs Wechselrichter und Batterien fügst du jeden Wechselrichter oder Batteriestapel mit Name, Modell (Voltronic, MPP Solar, Pylontech US2000 / US3000 / US5000, ANT-BMS), Anschluss (RS232, RS485, USB, CAN, WLAN) und Gateway-Knoten hinzu; es wartet auf seinen ersten echten Messwert, und mit *Beispielwerte zeigen* lässt sich das Menü inzwischen ausprobieren.",
        ],
        "sections": [
            {"title": "Sicherheitsmodell", "bullets": [
                "**Keine Geheimnisse im Browser.** Kamerapasswörter werden einmal eingegeben, an den Server gesendet und danach nur als maskierter Zustand „gespeichert“ gezeigt. Standortexporte lassen Benutzernamen und Zugangsdaten-Markierungen weg.",
                "**Gespeicherte Einstellungen sind nicht vertrauenswürdige Eingabe.** Sie werden Wert für Wert gelesen: ein ungültiger Ursprung, ein ungültiges Thema, eine ungültige Sprache oder Form wird verworfen, Positionen werden begrenzt und Listen gekappt.",
                "**Keine Anfragen an Dritte.** Schriften sind lokal; der statische Host sendet `Content-Security-Policy: default-src 'self'` beschränkt auf den konfigurierten Server, `frame-ancestors 'none'`, `nosniff` und `no-referrer`.",
                "Live-Video wird nur über eine Stream-Adresse gezeigt, die der Server einem Operator ausstellt.",
            ]},
        ],
        "note": "`tools/serve.mjs` liest `ARMOR_STUDIO_HOST` (Standard `127.0.0.1`), `ARMOR_STUDIO_PORT` (`5178`), `ARMOR_STUDIO_DIST` und `ARMOR_SERVER_ORIGIN`. Zur Installation des ganzen Stacks auf dem CM5-Prüfstand siehe [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-COMMON": {
        "tagline": "Nachrichtenverträge, Validierung und der gemeinsame Projektstarter",
        "honest": "Die Schemas, der Python-Validierer, die 147 gemeinsamen Konformitätsvektoren, die generierten TypeScript- und Kotlin-Typen und der gemeinsame Projektstarter sind real und getestet (19 Tests). Die Kotlin-Datei ist generiert, wird aber von ARMOR-ANDROID-CONTROL **noch nicht verwendet**, und der Befehl `set_thresholds` trägt nur ein Feld `sensitivity`, weil die echten Radarparameter erst definiert werden, wenn es Firmware gibt.",
        "intro": "**ARMOR-COMMON** besitzt die Bedeutung jeder A.R.M.O.R.-Nachricht. Radarknoten, Solar-Gateway-Knoten und der Simulator erzeugen diese Nachrichten; der Server, die visuelle KI und der Sprachdienst verbrauchen sie. Wenn zwei Projekte über ein Feld uneins sind, entscheidet dieses Repository.",
        "bullets": [
            "**Eine einzige Wahrheitsquelle:** JSON-Schemas in `src/armor_common/schemas/` für Telemetrie, Zustand, Befehl, Knoteninformation und die zwei Solarnachrichten (Wechselrichter, Batterie mit Zellen und Kapazitäten). Unbekannte Felder werden überall abgelehnt.",
            "**Ein Validierer, der keine Regel überspringen kann:** er interpretiert das Schema direkt und lehnt ein Schema ab, das ein nicht implementiertes Schlüsselwort nutzt.",
            "**Konformitätsvektoren:** 147 akzeptierte und abgelehnte Nutzlasten, von jeder Implementierung ausgeführt (hier Python, TypeScript in ARMOR-SERVER, die Prüfungen von ARMOR-SOLAR), sodass Abweichung den Build scheitern lässt.",
            "**Generierte Clients:** TypeScript- und Kotlin-Typen entstehen aus den Schemas (`tools/generate_types.py --check` hält sie aktuell).",
            "**HTTP-Vertrag:** `openapi/armor-server-0.2.0.yaml` beschreibt jede Serverroute, ihre Zugriffsregel und ihr Schema.",
            "**Gemeinsamer Starter:** `tools/armor_project_tool.py` gibt jedem Repository der Familie denselben Ablauf `build`, `build-test` und `run`.",
        ],
        "sections": [],
        "note": "Broker-Topics: `armor/node/{node_id}/telemetry | health | command | info` und `armor/solar/{node_id}/{device}/state`. Siehe den [Vertragsleitfaden](docs/CONTRACTS.md). Der gemeinsame Starter erzeugt beim ersten ARMOR-SERVER-Lauf eine ignorierte `.env` mit zufälligen Geheimnissen und einem zufälligen Administratorpasswort; nichts wird gedruckt oder eingecheckt.",
    },
    "ARMOR-DOCS": {
        "tagline": "Kanonische Architektur, Sicherheitsgrundlage und die Wahrheit darüber, was belegt ist",
        "honest": "Dieses Repository dokumentiert Schnittstellen und Verfahren, die validiert wurden, und sagt klar, was nicht. Lies die [Fähigkeitsmatrix](docs/CAPABILITY_MATRIX.md), bevor du glaubst, eine Funktion sei „fertig“: sie sagt für jede, ob sie nur simuliert, am Rechner getestet oder auf echter Hardware verifiziert wurde.",
        "intro": "",
        "bullets": [
            "[Fähigkeitsmatrix](docs/CAPABILITY_MATRIX.md): ist jede Fähigkeit simuliert, lokal oder auf Hardware verifiziert?",
            "[Architektur](docs/ARCHITECTURE.md): Netze, Vertrauensgrenzen, Zeit und Reihenfolge.",
            "[Sicherheitsgrundlage](docs/SECURITY_BASELINE.md): das VLAN-Design, was der Code durchsetzt und was noch fehlt.",
            "[Projektkatalog](docs/PROJECT_CATALOG.md): die zwölf Repositorys, ihre Versionen und wie sie voneinander abhängen.",
            "[Schnittstellen](docs/INTERFACES.md): wer jede Schnittstelle erzeugt und verbraucht und wo ihr vertraut wird.",
            "[Erster vertikaler Schnitt](docs/FIRST_VERTICAL_SLICE.md): was der Test vom Simulator bis zur Konsole belegt und was nicht.",
            "**Werkzeuge:** `make_readmes.py` schreibt das README jedes Repositorys in sieben Sprachen, `make_brand.py` sein Banner und Symbol, `publication_check.py` sucht vor einer Veröffentlichung nach Privatem und `clean_history.py` erstellt eine veröffentlichbare Kopie eines Repositorys.",
        ],
        "sections": [],
        "note": "Die Audits der Familie (auf Spanisch) liegen im Stammverzeichnis dieses Repositorys.",
    },
}
