"""Français : les mots autour de chaque README, la description d'une ligne de chaque dépôt et le texte de tous les dépôts.

Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
"""
from __future__ import annotations

UI = {
    "overview": "Présentation", "structure": "Structure du dépôt", "dev": "Environnement de développement", "architecture": "Architecture",
    "related": "Projets liés", "community": "Documentation et communauté", "author": "AUTEUR", "license": "LICENCE",
    "honesty": "Vérification d'honnêteté - ce qui fonctionne aujourd'hui", "license_text": "GPL-3.0-or-later - voir [LICENSE](LICENSE).",
    "family": "**A.R.M.O.R.** (Autonomous Radar & Multimodal Observation Range) est un système de sécurité périmétrique composé de dépôts indépendants. Chacun a sa propre version, ses propres tests et son propre README ; voici la famille :",
    "here": "ce dépôt",
    "docs_intro": "Pour en savoir plus :",
    "doc_matrix": "Matrice des capacités : ce qui est prouvé et ce qui ne l'est pas",
    "doc_catalog": "Catalogue des projets : versions et dépendances entre les dépôts",
    "doc_changelog": "Historique des modifications de ce dépôt",
    "doc_license": "Licence (GPL-3.0-or-later)",
    "contact": "Questions, idées et rapports : electrohobby3d@gmail.com",
}

RELATED = {
    "ARMOR-COMMON": "Contrats de messages, validateurs, vecteurs de conformité et types générés",
    "ARMOR-RADAR": "Firmware du nœud de terrain pour ESP32-S3 avec trois radars et son propre panneau web",
    "ARMOR-SOLAR": "Protocoles des onduleurs et batteries solaires et messages d'un nœud passerelle",
    "ARMOR-SERVER": "Coordinateur central : télémétrie, alarmes, appareils, relevés solaires et caméras",
    "ARMOR-STUDIO": "Console web : caméras, radar, alarmes, énergie solaire et concepteur de site 2D/3D",
    "ARMOR-ANDROID-CONTROL": "Client Android de l'opérateur avec radar 2D/3D en direct",
    "ARMOR-SERVER-AI": "Politique d'inférence visuelle qui explique ses décisions et n'agit jamais",
    "ARMOR-VOICE-AI": "Intentions vocales hors ligne avec une confirmation impossible à falsifier",
    "ARMOR-HARDWARE": "Boîtiers, électronique et matrice d'acceptation sur banc",
    "ARMOR-DEVOPS": "Déploiement, banc d'essai CM5, sauvegarde et TLS",
    "ARMOR-SIMULATOR": "Simulateur de télémétrie hors ligne avec des pannes reproductibles",
    "ARMOR-DOCS": "Architecture, base de sécurité et matrice des capacités",
}

TEXT = {
    "ARMOR-SIMULATOR": {
        "tagline": "Simulateur de télémétrie hors ligne avec des pannes reproductibles",
        "honest": "Les scénarios, les pannes, l'envoi vers un serveur et les 26 tests sont réels. La géométrie est **illustrative**, pas un modèle du vrai radar LD2450, et rien n'a été comparé à du matériel réel.",
        "bullets": [
            "**Scénarios :** `patrol`, `crossing`, `two-intruders` et `empty`, sur une géométrie d'angle à trois capteurs, avec un cycle de lumière jour/nuit ou une nuit fixe.",
            "**Pannes reproductibles :** un nœud muet, des messages désordonnés ou dupliqués, un nœud instable et des messages volontairement invalides (lux hors limite, champ inconnu, trop de pistes) pour les tests négatifs.",
            "**Déterministe :** la même graine imprime toujours les mêmes lignes ; rien n'est envoyé sans `--server-url` et `--ingest-token`.",
            "**Vérifié contre le contrat :** `--validate` fait passer chaque message par ARMOR-COMMON avant de l'émettre.",
            "**Envoi prudent :** seule une origine http(s) simple est acceptée ; une erreur 4xx arrête l'exécution, une 5xx ou une erreur réseau est retentée.",
            "**Équipement solaire :** `--solar` ajoute un onduleur et une pile de batteries de deux modules (quinze cellules chacun, capacités comprises) sur une journée accélérée de 240 échantillons, avec une coupure du réseau en fin de journée ; les messages sont vérifiés contre le contrat solaire d'ARMOR-COMMON et envoyés à `/api/v1/solar`.",
        ],
        "note": "Toutes les options, scénarios et pannes : [utilisation](docs/USAGE.md).",
    },
    "ARMOR-SERVER-AI": {
        "tagline": "Politique d'inférence visuelle : elle décide et explique, sans jamais agir",
        "honest": "La couche de décision est réelle et testée (26 tests). **Rien ici ne fait encore tourner une caméra, du RTSP ou TensorRT** : cela demande le Jetson, et ce n'est pas prouvé.",
        "bullets": [
            "**Profil jour/nuit avec hystérésis :** faible luminosité sous 30 lux, retour au jour seulement au-dessus de 60 lux et jamais deux fois en 30 s, pour que le crépuscule ne le fasse pas osciller.",
            "**Fusion explicable :** chaque détection et les pistes radar donnent une gravité (`ignore`, `review`, `high`) avec les raisons. Une personne vue à 80 % ou plus **et** une piste radar donnent `high` ; la faible luminosité abaisse seulement le seuil de revue ; une détection de plus de 10 s est ignorée.",
            "**Recommandations seulement :** une décision porte toujours `authorizes_action = false`. Le serveur central authentifie et autorise chaque action.",
            "**Moteurs vérifiés par somme de contrôle :** les moteurs TensorRT pré-compilés ne sont acceptés que s'ils existent, ne sont pas vides et, avec un `engines.json`, correspondent à leur SHA-256. Rien n'est compilé ni téléchargé.",
            "**Worker JSONL :** résultats numérotés et expliqués ; une ligne invalide signale son numéro et n'arrête jamais le flux.",
        ],
        "note": "Voir la [frontière d'inférence](docs/INFERENCE_BOUNDARY.md).",
    },
    "ARMOR-VOICE-AI": {
        "tagline": "Intentions vocales hors ligne avec une confirmation que l'appelant ne peut pas falsifier",
        "honest": "Les règles d'intention, la confirmation signée et l'audit sont réels et testés (20 tests). **Aucun moteur de reconnaissance ni de synthèse vocale ne fait encore partie de ce dépôt.**",
        "bullets": [
            "**Une liste fermée :** `status`, `silence`, `arm` et `disarm`, en anglais et en espagnol, après normalisation des accents, de la ponctuation et des formules de politesse. Tout le reste, ou tout ce qui est ambigu, n'est pas compris.",
            "**Une confirmation émise par le service :** `arm` et `disarm` renvoient un jeton signé au premier tour et ne sont acceptés que si un tour suivant le renvoie pour la même intention en moins de 30 s. Il ne peut être ni falsifié, ni redirigé, ni réutilisé, ni remplacé par un simple `confirmed: true` (refusé).",
            "**Des décisions, pas de l'audio :** avec `--audit-file`, chaque décision enregistre l'intention, le résultat et un SHA-256 de la transcription, jamais l'audio ni les mots bruts.",
            "**Recommandations seulement :** une commande acceptée est transmise à ARMOR-SERVER, qui l'authentifie et l'autorise encore.",
        ],
        "note": "Voir la [sécurité vocale](docs/SAFETY.md).",
    },
    "ARMOR-SOLAR": {
        "tagline": "Nœud passerelle solaire : lit onduleurs et batteries par jusqu'à dix ports série (firmware ESP32-S3, son panneau web et la bibliothèque de protocoles)",
        "honest": "**Maturité : scaffolding.** Le firmware se compile dans le conteneur ESP-IDF 5.4.2, son cœur (les réglages, l'échange avec chaque type d'équipement, l'arithmétique de l'UART émulé : 349 contrôles) est testé sur ordinateur avec des équipements simulés, les messages qu'il produit sont acceptés par ARMOR-COMMON et le panneau a été essayé dans un navigateur face à un nœud simulé. **Il n'a jamais tourné sur une carte et aucun onduleur ni batterie n'a été connecté** : le Wi-Fi, le panneau en TLS, la mise à jour, les UART matériels et émulés et les formats des protocoles (écrits d'après des documents publics et de mémoire) sont inessayés. Les trames ANT-BMS des tests ont été capturées par d'autres sur leurs propres appareils : ce projet n'en a lu aucune lui-même.",
        "bullets": [
            "**Deux cartes, un firmware :** une ESP32-S3-WROOM-1 N16R8 en Wi-Fi (par défaut) et la Waveshare ESP32-S3-ETH sur son câble Ethernet (DHCP ou adresse fixe ; son propre réseau Wi-Fi est conservé pour la joindre depuis un téléphone). L'image se choisit à la compilation (`tools/build_node.sh generic s3-wifi` ou `generic s3-eth`) ; la table des broches, les broches par défaut des ports et l'accès suivent la carte, et une image ne vaut que pour sa carte. Les deux compilent et sont testées sur ordinateur ; aucune n'a tourné sur une carte.",
            "**Le firmware du nœud** (ESP32-S3-WROOM-1 N16R8 en Wi-Fi, ou Waveshare ESP32-S3-ETH sur câble) : dix ports série, trois UART matériels et sept émulés (jusqu'à 19200 bauds), chacun indépendant et lisant un onduleur, une batterie ou un moniteur brut, si bien qu'un nœud peut lire seulement des onduleurs, seulement des batteries ou un mélange.",
            "**Le panneau web du nœud,** celui des nœuds radar aussi : configuration avec un code affiché sur la console USB, connexion et utilisateurs, Wi-Fi (station et point d'accès), broker, mise à jour par radio avec retour arrière, journal, HTTPS, et les pages des ports (avec ce que chacun entend, pour les protocoles pas encore décodés) et des relevés, en sept langues.",
            "**Onduleurs Voltronic / MPP Solar** (Axpert, PIP, InfiniSolar et clones), RS232 à 2400 bauds : les trames et leur CRC, et les relevés `QPIGS` (réseau, sortie, batterie, PV, bits d'état), `QMOD` (mode), `QPIWS` (avertissements et pannes par nom) et `QPIRI` (valeurs nominales). Seules les commandes de lecture peuvent être construites : un réglage change la façon dont la maison est alimentée.",
            "**Batteries Pylontech** (US2000, US3000, US5000) : le tableau `pwr` de la console (tension, courant, températures et état de charge de chaque module), `bat <n>` (tension et température de chaque cellule) et `info <n>` (modèle, capacité restante et totale, cycles), résumés en une pile avec sa capacité et son énergie totales, et la trame RS485 avec ses deux contrôles. Les formats sont écrits de mémoire de la console publique et peuvent varier selon les firmwares.",
            "**Les messages du nœud** (`armor/solar/<nœud>/<appareil>/state`, un par onduleur ou pile de batteries), définis dans ARMOR-COMMON avec schémas et vecteurs de conformité ; ce que produisent les ports est vérifié contre eux.",
            "**Batteries ANT-BMS** (les cartes noires des packs faits maison, 7S à 32S), UART 3,3 V à 19200 bauds : les deux protocoles de son firmware (le nœud demande dans l'un puis dans l'autre et garde celui qui répond), avec les cellules, les températures, l'état de charge, le courant, les capacités et les états des MOSFET et de l'équilibreur, vérifiés sur des trames capturées sur quatre modèles réels. Lecture seule : ses commandes d'écriture peuvent déconnecter une batterie en charge.",
            "**Pas encore :** la liaison Bluetooth de l'ANT-BMS (le nœud utilise le câble, le plus stable des deux), l'onglet Android et un essai sur une vraie carte avec de vrais équipements.",
        ],
        "note": "Voir le [guide du firmware](docs/NODE_FIRMWARE.md) (la carte, les ports, le premier démarrage et la liste d'essais sur banc) et les [notes de câblage](docs/NODE_HARDWARE.md).",
    },
    "ARMOR-RADAR": {
        "tagline": "Firmware de nœud de terrain (Waveshare ESP32-S3-ETH, trois radars ou capteurs de présence, Ethernet et Wi-Fi) avec son propre panneau web, et son cœur testé sur ordinateur",
        "honest": "**Maturité : scaffolding.** Le cœur indépendant du matériel (859 contrôles : les décodeurs du LD2450, du LD2461 et de quatre capteurs de présence, le canal de commande du LD2450, les réglages et leurs vérifications, la table des broches, les utilisateurs et sessions, la logique des broches associées, le plan réseau et le sérialiseur de messages, dont la sortie est acceptée par ARMOR-COMMON) est testé sur ordinateur, le **panneau web** a été essayé dans un vrai navigateur face à un nœud simulé, et l'**image du firmware se compile** dans le conteneur ESP-IDF 5.4.2. **Il n'a jamais tourné sur une carte** : aucune trame n'a été capturée depuis un vrai module, le code Ethernet, pont Wi-Fi, capteur de lumière et mise à jour est inessayé, le canal de commande des radars n'est vérifié ni face au document du fabricant ni face à un module, le certificat HTTPS du panneau est fabriqué par le nœud lui-même et inessayé dans un vrai navigateur, et les décodeurs du LD2461 et des capteurs de présence ne correspondent qu'aux exemples de leurs manuels, sans module réel.",
        "bullets": [
            "**Deux cartes, un firmware :** la Waveshare ESP32-S3-ETH (Ethernet, par défaut) et une ESP32-S3-WROOM-1 N16R8 sans Ethernet (Wi-Fi seul : sa configuration demande le réseau Wi-Fi à rejoindre et le nœud garde toujours son propre réseau). L'image se choisit à la compilation (`tools/build_node.sh generic s3-eth` ou `generic s3-wifi`) ; la table des broches et l'accès suivent la carte, le panneau masque ce que la carte n'a pas, et une image ne vaut que pour sa carte. Les deux compilent et sont testées sur ordinateur ; aucune n'a tourné sur une carte.",
            "**Deux nœuds de 270 degrés :** chaque Waveshare ESP32-S3-ETH lit jusqu'à trois radars LD2450 sur ses trois UART, montés à 75 degrés l'un de l'autre, par Ethernet filaire (W5500) en DHCP ou adresse fixe, alimenté en PoE ou USB. *Add a 270° node* de Studio crée les trois radars déjà associés au nœud.",
            "**Un panneau web sur chaque nœud,** à l'apparence de Studio et en sept langues, intégré au firmware : vue d'ensemble, réseau, Wi-Fi, broker, radars, broches, utilisateurs, mise à jour du firmware et journal. Un nœud sans utilisateur ouvre le Wi-Fi `ARMOR-SETUP-xxxxxx` et crée son premier administrateur avec un code d'installation ; les mots de passe sont en PBKDF2 salé, les sessions sont des jetons aléatoires et tous les réglages sont dans la flash du nœud, si bien qu'une image sert tous les nœuds et qu'aucun mot de passe n'est compilé ([le panneau](docs/NODE_PANEL.md)).",
            "**Un seul Wi-Fi à partir de plusieurs nœuds :** chaque nœud peut offrir un point d'accès relié à son port Ethernet ; avec le même nom et mot de passe et le canal en automatique (1, 6 ou 11 selon la MAC), téléphones et capteurs Wi-Fi voient un seul réseau avec un seul serveur DHCP. Ce n'est pas un maillage radio : chaque nœud garde son câble. Un nœud peut aussi rejoindre le Wi-Fi d'un routeur (avec recherche de réseaux), et un nœud sans câble peut être configuré en **Bluetooth** depuis l'application Android.",
            "**Broches pour le serveur :** toute broche libre devient une entrée, une sortie (avec un état sûr si le broker est perdu), du PWM ou une lecture analogique, et apparaît comme un appareil du serveur : un relais ou un contact n'exige aucun nouveau firmware. Les broches réservées de la carte ne sont jamais proposées.",
            "**Mises à jour par radio (OTA) avec retour arrière** depuis le panneau (deux emplacements sur la flash de 16 Mo), et un **lien depuis Studio** vers le panneau de chaque nœud, à partir de l'adresse que le nœud publie.",
            "**Le panneau en HTTPS :** le nœud fabrique son propre certificat (auto-signé, conservé en flash) et sert le panneau sur le port 443 en plus du 80, ou seulement sur le 443 ; le cookie de session est marqué Secure et l'empreinte du certificat s'affiche pour la comparer à l'avertissement du navigateur. **Identités de pistes stables :** les cibles de chaque trame sont associées à celles suivies auparavant ; une personne garde donc le même identifiant, une trame perdue ne fait pas clignoter et les positions sont un peu lissées.",
            "**Six modèles de capteurs, un par port :** un port porte un LD2450 ou un LD2461 (traqueurs qui alimentent le périmètre, avec le champ propre du modèle dans Studio) ou un capteur de présence (LD2410, LD2412, LD2410S, MR24HPC1) qui devient un appareil du serveur et publie présence et distance. Choisi dans le panneau ; ce qu'est chacun, son protocole et ce qui n'a pas été vérifié sont dans `docs/SENSORS.md`.",
            "**Décodeur, santé et configuration du LD2450 :** un découpeur qui se resynchronise trouve les trames dans un flux bruité ; chaque trame de 30 octets donne jusqu'à trois cibles qui deviennent des pistes du contrat ; la console et le panneau indiquent par radar s'il émet, se tait ou envoie des données illisibles. Le panneau peut aussi lire la version du module, choisir une ou trois cibles et définir des zones de détection (un protocole non vérifié face à un module).",
            "**Lumière ambiante et messages conformes au contrat :** le VEML7700 avec plage automatique ; JSON de télémétrie, de santé et d'information qui suit les schémas publiés et refuse d'écrire quoi que ce soit d'invalide, avec des horodatages d'horloge murale (SNTP) et un testament MQTT. La télémétrie est retenue tant qu'aucun radar n'émet, jamais un « tout est calme » vide.",
            "**Une image pour toutes les cartes, comme un produit réseau :** le firmware est le même et l'adresse MAC distingue les cartes (`armor-` et six chiffres jusqu'au nommage) ; `adopt_node.py` donne à un nœud fraîchement flashé son administrateur, son identité de broker et les réglages communs de la flotte par le réseau, avec un code d'installation calculé depuis sa MAC : 5 nœuds ou 27, c'est le même travail. **Outils de banc :** flashage par USB-C, un nœud simulé pour travailler sur le panneau et un convertisseur d'un journal de trames brutes en jeu de test ([mise en service sur banc](docs/BENCH_BRINGUP.md)).",
        ],
        "note": "Les tests sur ordinateur demandent un compilateur C++17 (Linux, WSL, MSYS2). Voir la [mise en service sur banc](docs/BENCH_BRINGUP.md), le [panneau](docs/NODE_PANEL.md) et la [frontière matérielle](docs/HARDWARE_BOUNDARY.md).",
    },
    "ARMOR-ANDROID-CONTROL": {
        "tagline": "Client mobile de l'opérateur pour ARMOR-SERVER",
        "honest": "Les règles de sûreté des adresses et de décision d'alarme ont des tests unitaires (55) et l'application se compile. Elle **n'a pas été exécutée sur un téléphone face au serveur** : le flux d'autorisation des notifications et le service en arrière-plan ne sont donc pas vérifiés. Armement, alarmes et appareils suivent les routes du serveur mais n'ont pas été essayés sur un vrai téléphone.",
        "bullets": [
            "**Connexion avec l'identifiant du serveur :** IP, port, utilisateur et mot de passe ; le mot de passe crée une session HttpOnly et n'est jamais conservé sur le téléphone.",
            "**Moniteur de caméras :** 1 à 16 vignettes, une vue agrandie, MJPEG en direct qui garde le rapport d'image, une manette PTZ bornée, captures et enregistrements.",
            "**Armer et désarmer,** après confirmation ; **alarmes** à acquitter, avec un badge pour celles en attente ; **appareils** (fumée, gaz, inondation, porte, fenêtre, mouvement, climat, prises, lumières, sirènes, serrures) avec leur état et On / Off / Basculer.",
            "**Radar en direct, en 2D et en 3D :** l'onglet Radar dessine le site tel que conçu dans Studio (sol, bâtiments, arbres, poteaux, champs des radars et des caméras) et les personnes que les radars voient bouger, rafraîchi toutes les secondes et demie ; glisser, pincer et tourner la vue 3D. Le placement suit les règles de Studio, mais n'a jamais montré un vrai radar.",
            "**Solaire :** une entrée dans *Más* (et une tuile dans l'écran d'état) montre les totaux (soleil, consommation, batteries avec leur charge et leur flux, présence du réseau) et chaque onduleur et batterie que le serveur signale : leurs valeurs, les cellules d'une batterie à la demande avec la plus haute et la plus basse marquées, les équipements qui attendent encore des données, et une marque sur une mesure d'exemple ou un équipement muet. Actualisé toutes les cinq secondes tant qu'il est ouvert ; testé sur les formes de réponse du serveur et essayé dans un émulateur face à un serveur local avec des mesures d'exemple, jamais avec de vrais équipements. Les alarmes solaires (panne d'onduleur, batterie faible ou en protection, équipement muet) réveillent le téléphone comme celles d'un appareil.",
            "**Configurer un nœud de terrain en Bluetooth** (depuis l'écran de connexion ou *Más > Configurar un nodo*) : trouve les nœuds qui annoncent `ARMOR-xxxxxx`, crée l'administrateur d'un nouveau ou se connecte, cherche des réseaux Wi-Fi et règle le nom du nœud, le Wi-Fi d'un routeur ou une adresse fixe et le broker, pour les nœuds sans câble Ethernet. Compilé et testé unitairement, jamais exécuté face à un nœud ni un téléphone.",
            "**Bibliothèque de preuves,** état du périmètre et des nœuds, et **historique** de chaque alerte, nœud, caméra, appareil, alarme et changement de mode.",
            "**Notifications d'alarme** pour un nœud qui atteint HIGH, une caméra qui ne répond plus, une alarme d'appareil (fumée, gaz, inondation, panique à tout moment ; une porte, fenêtre ou un capteur de mouvement pendant l'armement) et, armé, un nœud qui se déconnecte ; une veille facultative en arrière-plan utilise la session en cours et le signale quand elle se termine.",
            "**Prudence avec le mot de passe :** le HTTP simple n'est permis que vers un *littéral* IPv4 de réseau local privé ou de bouclage. Un nom d'hôte qui commence seulement comme une adresse privée (`10.attacker.example`) ou une adresse avec un zéro initial (certains résolveurs lisent `010.0.0.1` comme la publique `8.0.0.1`) est refusé.",
            "**Un aspect fait d'icônes :** surfaces presque noires, accent cyan, ambre pour l'attention, grandes icônes avec peu de mots, barre inférieure, page À propos et bouton de déconnexion.",
        ],
        "note": "L'APK de débogage n'est pas signé pour la distribution. Voir la [frontière du client](docs/CLIENT_BOUNDARY.md).",
    },
    "ARMOR-HARDWARE": {
        "tagline": "Boîtiers, électronique et matrice d'acceptation sur banc",
        "honest": "Le boîtier est un **point de départ mécanique imprimable, pas une certification IP, RF ou thermique.** Rien n'a été mesuré sur un prototype ; chaque ligne de la [matrice d'acceptation sur banc](docs/BENCH_ACCEPTANCE.md) est *non testée*.",
        "bullets": [
            "**Le vrai design est `CAD/CARCASA_SENSORES.scad`** (avec exports STL, 3MF et AMF) : une base d'angle à 90 degrés avec visière, toit et fond, des gradins de retenue, un couvercle frontal coulissant de 2 mm et des rabats latéraux, le tout piloté par des paramètres nommés. `scad/node_enclosure.scad` n'est qu'une boîte provisoire.",
            "**Volumes réservés** pour trois modules radar, la carte ESP32-S3-ETH-PoE, la fenêtre du capteur, un presse-étoupe, les magnétiques PoE et le réchauffeur PTC. Aucun matériau métallique, conducteur ou chargé de carbone devant une ouverture 24 GHz sans atténuation mesurée.",
            "**Matrice d'acceptation sur banc :** les contrôles radio, environnement, alimentation, réseau et caméra, chacun avec une méthode et un critère de réussite proposé, et un tableau de compatibilité des caméras à remplir.",
            "Avant la fabrication, consigner les contours exacts des cartes, les connecteurs, la position des vis, les zones d'exclusion d'antenne, le chemin thermique et l'objectif d'étanchéité ([données de conception](docs/DESIGN_INPUTS.md)).",
        ],
        "note": "Voir la [frontière de validation](docs/VALIDATION.md). La licence matérielle prévue est CERN-OHL-S-2.0 ; ajoutez son texte complet avant de publier les designs.",
    },
    "ARMOR-DEVOPS": {
        "tagline": "Topologie de déploiement et banc d'essai CM5 isolé",
        "honest": "L'installateur du banc CM5 a été exécuté sur une vraie CM5 qui héberge d'autres logiciels, restés en bonne santé. La topologie Docker Compose et son profil TLS facultatif ont été construits et exécutés pour de vrai avec Docker Engine dans WSL (`scripts/test_compose.sh`, 12 contrôles, qui ont trouvé et corrigé trois défauts), mais **pas sur le Jetson**. Les scripts de sauvegarde et de restauration ont un test aller-retour réussi.",
        "bullets": [
            "**Un pare-feu de la machine centrale** (`scripts/firewall_core.sh`) : le port du broker seulement depuis le réseau de terrain, ceux du serveur et de Studio seulement depuis le réseau des clients (s'il est donné), dans une table à part qui ne mentionne rien d'autre et accepte le reste ; `apply --rollback-after` retire de nouveau les règles si vous ne les confirmez pas, une erreur ne peut donc pas vous enfermer dehors. Les règles et les refus sont testés (36 contrôles, rien n'est chargé) ; il n'a été chargé sur aucune machine, et les VLAN eux-mêmes restent un plan pour le routeur et le commutateur.",
            "**Banc d'essai CM5 :** `scripts/deploy_cm5.sh` construit dans une copie propre, envoie une archive et exécute `scripts/install_cm5.sh`, qui crée son propre utilisateur, son propre répertoire et deux unités systemd sur leurs propres ports (trois avec `--with-mqtt` : le Mosquitto propre d'A.R.M.O.R. sur le port 18883, vérifié sur une vraie CM5), avec des limites de ressources, et ne touche jamais un autre projet ([détails](docs/CM5_TEST_BENCH.md)).",
            "**Topologie Compose :** un broker Mosquitto non anonyme avec une identité par nœud, le serveur, et Studio derrière un nginx qui relaie `/api/` ; seul Studio est publié, sur le bouclage. Conteneurs durcis, réseau interne pour le cœur et volumes nommés pour l'état.",
            "**Appareils et relevés sur le broker du banc :** le serveur peut écouter et commander `armor/device/#` et lire `armor/node/+/info` et `armor/solar/#` ; `scripts/mqtt_identity.sh add device NAME` donne à un appareil ses propres sujets et `add bridge NAME` à un pont Zigbee2MQTT ou Shelly tous les sujets.",
            "**Secrets :** `scripts/generate_secrets.sh` crée des secrets aléatoires sans en afficher ; `scripts/check-required-env.sh` refuse les valeurs absentes, d'exemple, courtes ou répétées.",
            "**Sauvegarde et restauration :** `scripts/backup_data.sh` crée une archive chiffrée AES-256, vérifiée et avec somme de contrôle des données du serveur (sans les preuves sauf demande) ; `scripts/restore_data.sh` la liste ou la restaure sans jamais écraser de données existantes. La clé des caméras n'est volontairement **pas** dans l'archive.",
            "**TLS :** un profil Compose `tls` facultatif place Caddy, avec sa propre autorité de certification locale, devant Studio ([détails](docs/BACKUP_AND_TLS.md)).",
        ],
        "note": "Voir la [frontière de déploiement](docs/DEPLOYMENT_BOUNDARY.md).",
    },
    "ARMOR-SERVER": {
        "tagline": "Coordinateur central de sécurité : entrée de télémétrie, alarmes, appareils, relevés solaires et passerelle de caméras",
        "honest": "Chaque route, session, chiffrement et règle de preuves ci-dessous est réel et couvert par des tests (`npm test`, 161 tests, dont une suite d'intégration HTTP complète face à un serveur isolé). Il a fonctionné avec un vrai broker MQTT sur la CM5 (avec des scripts, pas avec un firmware de nœud de terrain), a diffusé de la vidéo en direct, enregistré une capture et filmé depuis cinq vraies caméras IP via FFmpeg. Ce qui n'est **pas encore prouvé** : ONVIF avec une vraie caméra ONVIF, le PTZ sur chaque firmware de caméra (il marche sur l'unité Hi3510), tout matériel Jetson et les routes solaires avec un vrai nœud passerelle (elles sont testées avec des relevés générés).",
        "intro": "**ARMOR-SERVER** est le centre de confiance d'A.R.M.O.R. Les nœuds de terrain publient des observations de radar, de lumière et de santé ; ce service les valide, garde le dernier état connu de chaque nœud et le sert à la console Studio et au client Android. Il possède aussi tout ce qui touche une caméra, de sorte qu'**aucun navigateur ni téléphone ne détient jamais un mot de passe de caméra ni une adresse RTSP**.",
        "bullets": [
            "**Entrée validée :** les observations HTTP et MQTT sont vérifiées à la frontière (identifiant, horodatages, plage de lux, 15 pistes au plus) avant d'atteindre la projection d'état.",
            "**État honnête des nœuds :** un nœud qui se tait est affiché *périmé* puis *hors ligne* après un délai configurable, jamais en ligne sur de vieilles données. Désarmer efface aussitôt une alerte haute.",
            "**Passerelle de caméras :** coffre de caméras chiffré, PTZ ONVIF / Hi3510 / PSIA, découverte des chemins RTSP, un relais FFmpeg partagé par caméra, captures et enregistrement MP4, et un chien de garde qui transforme une caméra muette en événement et, armé, en alarme.",
            "**Bibliothèque de preuves :** rétention par âge et par taille en commençant par les plus anciennes, **preuves protégées** jamais supprimées, et un SHA-256 pour la chaîne de conservation. Une ligne d'audit par action pertinente pour la sécurité, sans identifiants.",
            "**État qui survit :** le mode de sécurité et la dernière observation de chaque nœud sont restaurés après un redémarrage (un redémarrage ne désarme jamais le périmètre en silence). Chaque changement de niveau d'alerte, d'état de nœud et de mode est gardé dans un historique d'événements.",
            "**Sortie d'alarme :** les alertes hautes et, armé, les nœuds muets ou hors ligne vont vers MQTT `armor/server/alert` et un webhook facultatif signé HMAC ; le délai avant HIGH et les zones ignorées se règlent depuis Studio.",
            "**Utilisateurs :** noms et mots de passe (hachages scrypt), un rôle `admin` qui gère les utilisateurs et un rôle `operator` qui opère ; changer un mot de passe ou un rôle ferme les autres sessions de cet utilisateur.",
            "**Appareils, alarmes et automatisations :** appareils de fumée, gaz, inondation, porte, fenêtre, mouvement, climat, prise, lumière, sirène et serrure par MQTT ou envoi authentifié, avec état normalisé, disponibilité et commandes ; alarmes avec un cycle déclenchée / acquittée / effacée ; règles qui commandent des appareils lors d'un événement ; armer et désarmer depuis une session ouverte ; et le plan du site gardé sur le serveur pour tous les clients.",
            "**Relevés solaires :** les onduleurs et piles de batteries (avec chaque cellule et les capacités) arrivent par HTTP ou MQTT, sont validés par le contrat partagé, gardés avec un historique (un échantillon toutes les 30 s pendant un jour) et des totaux, marqués périmés après deux minutes, et déclenchent quatre alarmes (panne d'onduleur, batterie faible, alarme de batterie, appareil muet).",
        ],
        "sections": [
            {"title": "Modèle de sécurité", "bullets": [
                "Quatre secrets séparés : **ingestion** (envoi de télémétrie, santé et relevés solaires), **contrôle** (armer / désarmer, événements), **opérateur** (automatisation) et **connexion à Studio** ; chacun est comparé en temps constant et aucun ne remplace un autre.",
                "Toute route qui configure, déplace, capture, enregistre, protège ou supprime exige un opérateur. La vidéo en direct exige un opérateur ou un ticket de flux de courte durée lié à une caméra.",
                "Les mots de passe des caméras ne vivent que dans `data/cameras.json`, chiffrés en AES-256-GCM, et aucune API ne les renvoie ; les adresses ONVIF doivent rester sur l'hôte de la caméra et les redirections sont refusées.",
                "Les sessions Studio sont HttpOnly et SameSite=Strict pendant 8 heures, la connexion est limitée en débit et les erreurs ne portent jamais de trace de pile.",
                "Le serveur écoute sur 127.0.0.1 sauf si `ARMOR_HOST` est défini volontairement, et alors un mot de passe Studio de moins de 12 caractères est refusé.",
            ]},
            {"title": "API", "bullets": [
                "Publique : `GET /healthz`. Pour un opérateur : état, informations, caméras, médias, historique, règles, appareils, alarmes, automatisations, plan du site et `GET /api/v1/solar` avec son historique.",
                "Pour les nœuds de terrain et les passerelles : `POST /api/v1/telemetry`, `/health` et `/solar` avec le jeton d'ingestion, et les sujets MQTT `armor/node/#` et `armor/solar/#`. Les événements atteignent les consoles par le WebSocket `/api/v1/events`.",
                "Chaque route, sa règle d'accès et son schéma sont dans le fichier OpenAPI d'[ARMOR-COMMON](../ARMOR-COMMON), et un test vérifie qu'aucune route n'y manque.",
            ]},
            {"title": "Configuration", "bullets": [
                "Copiez `.env.example` vers `.env` (ignoré par Git), ou laissez `run.bat` / `run.sh` générer des secrets aléatoires au premier lancement.",
                "Obligatoires : `ARMOR_INGEST_TOKEN` et `ARMOR_CONTROL_TOKEN` (24 caractères ou plus, tous différents) et `ARMOR_STUDIO_USERNAME` / `ARMOR_STUDIO_PASSWORD` (le premier administrateur).",
                "Courantes : `ARMOR_HOST` / `ARMOR_PORT`, `ARMOR_DATA_DIR`, `ARMOR_FFMPEG_PATH` (vidéo en direct et capture), `ARMOR_MQTT_URL`, `ARMOR_STUDIO_ORIGIN`, `ARMOR_NODE_STALE_AFTER_S`, `ARMOR_CAMERA_CHECK_S`, `ARMOR_ALERT_DWELL_MS`, `ARMOR_ALERT_WEBHOOK_URL` et `ARMOR_COOKIE_SECURE` (à `1` derrière TLS).",
            ]},
        ],
        "note": "Pour installer sur le banc d'essai CM5 (isolé de tout autre projet, avec utilisateur et ports propres), voir [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-STUDIO": {
        "tagline": "Console d'exploitation et de conception : caméras, radar, alarmes, énergie solaire, preuves et plan du site",
        "honest": "Studio dialogue avec [ARMOR-SERVER](../ARMOR-SERVER) et est couvert par 176 tests unitaires (lecture des réglages, fusion des caméras, arithmétique des graphiques solaires, chaque menu affiché dans les sept langues, hôte statique). Ne sont **pas** prouvés : la vidéo en direct et le PTZ avec chaque vraie caméra, les menus solaires avec un vrai onduleur ou une vraie batterie, ni une revue formelle d'accessibilité ou d'utilisabilité. Tant que le serveur est injoignable, Studio affiche des données de démonstration et le dit dans la barre supérieure.",
        "intro": "**ARMOR-STUDIO** est la console de l'opérateur. Elle ne détient jamais un mot de passe de caméra, une adresse RTSP ni un jeton : elle se connecte au serveur avec un nom et un mot de passe, reçoit une session **HttpOnly** de 8 heures, et tout ce qui est privilégié passe par cette session.",
        "bullets": [
            "**Moniteur de caméras :** 1, 2, 4, 6, 8, 9, 12 ou 16 vignettes qui s'ajustent à leur cadre (16:9, toute la matrice visible, sans rognage), une vue agrandie avec manette PTZ bornée, capture et enregistrement MP4 ; une **bibliothèque d'enregistrements** pour filtrer, prévisualiser, lire, protéger et supprimer les preuves.",
            "**Alarmes, appareils et automatisations :** ce qui exige une personne maintenant avec acquittement et le registre clos ; appareils de fumée, gaz, inondation, porte, fenêtre, mouvement, climat, prise, lumière, sirène et serrure par Wi-Fi, Zigbee, Bluetooth ou câble (préréglages Zigbee2MQTT, Tasmota et Shelly) ; règles qui commandent des appareils lors d'un événement ; un grand bouton armer / désarmer.",
            "**Énergie solaire :** le menu *Onduleurs* dessine la maison comme un flux d'énergie animé (panneaux, réseau, onduleur, batterie et charge, avec des tirets d'autant plus rapides que la puissance est grande), jauges, relevés, avertissements en toutes lettres et graphiques d'historique ; le menu *Batteries* montre chaque pile avec un niveau de liquide, ses **capacités** (restante et totale, Ah et kWh, cycles, modèle), chaque module et **chaque cellule** en barre avec sa tension et l'écart en millivolts, et des graphiques de charge, tension, courant, plage des cellules et température.",
            "**Vue d'ensemble et système :** l'état du périmètre, une tuile par partie, une carte vivante du plan avec chaque appareil et une page système avec la piste d'audit pour un administrateur.",
            "**Radar :** une carte en direct dessinée à partir de votre plan du site (terrain, bâtiments, caméras, radars et leur couverture) avec les cibles que chaque radar rapporte, leur trajet récent et les zones ignorées ; état des nœuds en direct, les nœuds muets étant *périmés* ; le panneau propre de chaque nœud est à un clic.",
            "**Concepteur de site :** dessinez le terrain (rectangle ou forme quelconque, avec longueurs saisies), placez des bâtiments de plusieurs étages avec cinq types de toit, portes et fenêtres à tout étage et hauteur, lampadaires, cheminées, panneaux solaires, antennes, piliers, mâts, routes et chemins, puis caméras et radars où vous voulez ; un plan 2D de type CAO et une vue 3D que l'on peut orbiter, couper étage par étage et modifier ; annuler et rétablir.",
            "**Configuration :** adresse du serveur, caméras (ONVIF/RTSP), découverte, utilisateurs (votre compte et, pour un administrateur, la liste des utilisateurs, rôles et mots de passe), thème et langue ; un export portable du site **sans identifiants**.",
            "**Sept langues** (anglais, espagnol, allemand, français, italien, japonais, chinois) et onze thèmes, celui par défaut s'appelant *Armor*.",
            "**Déclarez votre équipement :** dans les menus Onduleurs et Batteries, vous ajoutez chaque onduleur ou pile de batteries avec son nom, son modèle (Voltronic, MPP Solar, Pylontech US2000 / US3000 / US5000, ANT-BMS), sa connexion (RS232, RS485, USB, CAN, Wi-Fi) et son nœud passerelle ; il attend son premier relevé réel, et *Voir des relevés d'exemple* permet d'essayer le menu en attendant.",
        ],
        "sections": [
            {"title": "Modèle de sécurité", "bullets": [
                "**Aucun secret dans le navigateur.** Les mots de passe des caméras sont saisis une fois, envoyés au serveur et ensuite affichés seulement comme un état « enregistré » masqué. Les exports du site suppriment les noms d'utilisateur et les indicateurs d'identifiants.",
                "**Les réglages stockés sont une entrée non fiable.** Ils sont lus valeur par valeur : une origine, un thème, une langue ou une forme invalides sont écartés, les positions sont bornées et les listes plafonnées.",
                "**Aucune requête vers un tiers.** Les polices sont locales ; l'hôte statique envoie `Content-Security-Policy: default-src 'self'` limitée au serveur configuré, `frame-ancestors 'none'`, `nosniff` et `no-referrer`.",
                "La vidéo en direct n'est montrée que par une adresse de flux que le serveur délivre à un opérateur.",
            ]},
        ],
        "note": "`tools/serve.mjs` lit `ARMOR_STUDIO_HOST` (par défaut `127.0.0.1`), `ARMOR_STUDIO_PORT` (`5178`), `ARMOR_STUDIO_DIST` et `ARMOR_SERVER_ORIGIN`. Pour installer toute la pile sur le banc d'essai CM5, voir [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-COMMON": {
        "tagline": "Contrats de messages, validation et lanceur de projets partagé",
        "honest": "Les schémas, le validateur Python, les 142 vecteurs de conformité partagés, les types TypeScript et Kotlin générés et le lanceur de projets partagé sont réels et testés (19 tests). Le fichier Kotlin est généré mais **pas encore utilisé** par ARMOR-ANDROID-CONTROL, et la commande `set_thresholds` ne porte qu'un champ `sensitivity` car les vrais paramètres du radar ne sont pas définis tant que le firmware n'existe pas.",
        "intro": "**ARMOR-COMMON** possède le sens de chaque message d'A.R.M.O.R. Les nœuds radar, les nœuds passerelles solaires et le simulateur produisent ces messages ; le serveur, l'IA visuelle et le service vocal les consomment. Si deux projets divergent sur un champ, ce dépôt tranche.",
        "bullets": [
            "**Une seule source de vérité :** des schémas JSON dans `src/armor_common/schemas/` pour la télémétrie, la santé, la commande, l'information du nœud et les deux messages solaires (onduleur, batterie avec cellules et capacités). Les champs inconnus sont rejetés partout.",
            "**Un validateur qui ne peut sauter aucune règle :** il interprète directement le schéma et refuse un schéma qui utilise un mot-clé qu'il n'implémente pas.",
            "**Vecteurs de conformité :** 142 charges acceptées et rejetées exécutées par chaque implémentation (Python ici, TypeScript dans ARMOR-SERVER, les contrôles d'ARMOR-SOLAR), si bien qu'une dérive fait échouer la compilation.",
            "**Clients générés :** les types TypeScript et Kotlin sortent des schémas (`tools/generate_types.py --check` les tient à jour).",
            "**Contrat HTTP :** `openapi/armor-server-0.2.0.yaml` décrit chaque route du serveur, sa règle d'accès et son schéma.",
            "**Lanceur partagé :** `tools/armor_project_tool.py` donne à tous les dépôts de la famille le même flux `build`, `build-test` et `run`.",
        ],
        "sections": [],
        "note": "Sujets du broker : `armor/node/{node_id}/telemetry | health | command | info` et `armor/solar/{node_id}/{device}/state`. Voir le [guide des contrats](docs/CONTRACTS.md). Le lanceur partagé crée un `.env` ignoré au premier lancement d'ARMOR-SERVER avec des secrets aléatoires et un mot de passe d'administrateur aléatoire ; rien n'est imprimé ni versionné.",
    },
    "ARMOR-DOCS": {
        "tagline": "Architecture canonique, base de sécurité et vérité sur ce qui est prouvé",
        "honest": "Ce dépôt documente des interfaces et des procédures validées, et dit franchement ce qui ne l'est pas. Lisez la [matrice des capacités](docs/CAPABILITY_MATRIX.md) avant de croire qu'une fonction est « terminée » : elle indique pour chacune si elle a seulement été simulée, testée sur ordinateur ou vérifiée sur du vrai matériel.",
        "intro": "",
        "bullets": [
            "[Matrice des capacités](docs/CAPABILITY_MATRIX.md) : pour chaque capacité, simulée, locale ou vérifiée sur matériel ?",
            "[Architecture](docs/ARCHITECTURE.md) : réseaux, frontières de confiance, temps et ordre.",
            "[Base de sécurité](docs/SECURITY_BASELINE.md) : la conception des VLAN, ce que le code impose et ce qui manque encore.",
            "[Catalogue des projets](docs/PROJECT_CATALOG.md) : les douze dépôts, leurs versions et leurs dépendances.",
            "[Interfaces](docs/INTERFACES.md) : qui produit et consomme chaque interface et où on lui fait confiance.",
            "[Première tranche verticale](docs/FIRST_VERTICAL_SLICE.md) : ce que prouve le test du simulateur à la console et ce qu'il ne prouve pas.",
            "**Outils :** `make_readmes.py` écrit le README de chaque dépôt en sept langues, `make_brand.py` sa bannière et son icône, `publication_check.py` cherche tout élément privé avant une publication et `clean_history.py` fait une copie publiable d'un dépôt.",
        ],
        "sections": [],
        "note": "Les audits de la famille (en espagnol) se trouvent à la racine de ce dépôt.",
    },
}
