"""Italiano: le parole attorno a ogni README, la descrizione di una riga di ogni repository e il testo di tutti i repository.

Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
"""
from __future__ import annotations

UI = {
    "overview": "Panoramica", "structure": "Struttura del repository", "dev": "Ambiente di sviluppo", "architecture": "Architettura",
    "related": "Progetti correlati", "community": "Documentazione e comunità", "author": "AUTORE", "license": "LICENZA",
    "honesty": "Controllo di onestà - cosa funziona oggi", "license_text": "GPL-3.0-or-later - vedi [LICENSE](LICENSE).",
    "family": "**A.R.M.O.R.** (Autonomous Radar & Multimodal Observation Range) è un sistema di sicurezza perimetrale fatto di repository indipendenti. Ognuno ha la propria versione, i propri test e il proprio README; ecco la famiglia:",
    "here": "questo repository",
    "docs_intro": "Dove leggere di più:",
    "doc_matrix": "Matrice delle capacità: cosa è provato e cosa no",
    "doc_catalog": "Catalogo dei progetti: versioni e dipendenze tra i repository",
    "doc_changelog": "Cronologia delle modifiche di questo repository",
    "doc_license": "Licenza (GPL-3.0-or-later)",
    "contact": "Domande, idee e segnalazioni: electrohobby3d@gmail.com",
}

RELATED = {
    "ARMOR-COMMON": "Contratti dei messaggi, validatori, vettori di conformità e tipi generati",
    "ARMOR-RADAR": "Firmware del nodo di campo per ESP32-S3 con tre radar e un proprio pannello web",
    "ARMOR-SOLAR": "Protocolli di inverter e batterie solari e messaggi di un nodo gateway",
    "ARMOR-ELECTRICAL": "Nodo elettrico: contatori, il messaggio delle letture della rete e le regole di manovra",
    "ARMOR-SERVER": "Coordinatore centrale: telemetria, allarmi, dispositivi, letture solari e telecamere",
    "ARMOR-STUDIO": "Console web: telecamere, radar, allarmi, energia solare e progettista del sito 2D/3D",
    "ARMOR-ANDROID-CONTROL": "Client Android dell'operatore con radar 2D/3D in tempo reale",
    "ARMOR-SERVER-AI": "Politica di inferenza visiva che spiega le sue decisioni e non agisce mai",
    "ARMOR-VOICE-AI": "Intenti vocali offline con una conferma impossibile da falsificare",
    "ARMOR-HARDWARE": "Contenitori, elettronica e matrice di accettazione da banco",
    "ARMOR-DEVOPS": "Distribuzione, banco di prova CM5, backup e TLS",
    "ARMOR-NETWORK": "La rete locale: i suoi dispositivi, internet e ciò che cambia",
    "ARMOR-SIMULATOR": "Simulatore di telemetria offline con guasti ripetibili",
    "ARMOR-UPDATER": "Rileva, installa e aggiorna i repository stessi dell'ecosistema",
    "ARMOR-DOCS": "Architettura, base di sicurezza e matrice delle capacità",
}

TEXT = {
    "ARMOR-UPDATER": {
        "tagline": "Rileva, installa e aggiorna ogni repository A.R.M.O.R. sulla macchina su cui viene eseguito (un programma Python senza dipendenze obbligatorie, costruito da zero per un ecosistema privato)",
        "honest": "**Maturità: impalcatura.** La scoperta tramite manifesto, il confronto delle versioni, l'installazione/aggiornamento atomico-per-verifica e il registro delle prove sono testati (103 test) sulla forma reale del manifesto di A.R.M.O.R.; non ha mai installato né aggiornato un vero repository A.R.M.O.R. dall'inizio alla fine, perché ognuno di essi è privato e ciò richiede un vero GITHUB_TOKEN che questo programma non ha ancora ricevuto.",
        "bullets": [
            "**Scoperta, senza elenco fisso:** una cartella locale entra a far parte dell'ecosistema non appena porta un `armor.project.json` valido che dichiara `ecosystem: \"A.R.M.O.R.\"`; da remoto, ogni repository che un `GITHUB_TOKEN` può vedere su GitHub viene controllato allo stesso modo - ogni repository A.R.M.O.R. è privato, quindi quel token è sempre obbligatorio, senza il ripiego di 60 richieste all'ora di un ecosistema pubblico.",
            "**Installare e aggiornare, mai sul posto:** un aggiornamento viene prima costruito e verificato in un clone di staging indipendente, e viene promosso - due rinomine di cartella, l'installazione precedente conservata come backup - solo quando quella build ha davvero successo; una modifica locale realmente non committata viene rifiutata subito, mai scartata in silenzio.",
            "**Prove:** ogni tentativo, riuscito o no, aggiunge una riga a un registro locale con il progetto, la versione e il commit prima e dopo, e il motivo di un fallimento.",
            "**Una CLI e un'interfaccia desktop opzionale:** `armor-updater status`/`install`/`update`, e un'interfaccia Qt Quick (`pip install \".[gui]\"`) nelle sette lingue dell'ecosistema.",
        ],
        "note": "Vedi `CONTRIBUTING.md` per come un repository entra a far parte dell'ecosistema descritto da `armor.project.json`.",
    },
    "ARMOR-NETWORK": {
        "tagline": "Sorveglia la rete locale: i dispositivi che ci sono, se internet c'è, cosa cambia e cosa è nuovo (un programma Python senza dipendenze, in sola lettura; gira su una macchina della rete e riferisce ad ARMOR-SERVER)",
        "honest": "**Maturità: scaffolding.** Lo scanner, l'inventario che dice cosa è cambiato, il controllo di internet e il messaggio sono provati su un computer contro una rete simulata (53 test; ARMOR-COMMON accetta tutti i messaggi), e il programma è stato eseguito una volta su una rete reale, con un router e un telefono. Non ha sorvegliato una casa intera per giorni, al router chiede soltanto e non lo configura mai, e ciò che è un dispositivo (tipo, sistema, produttore) è un'ipotesi. Non cattura pacchetti: non vede chi parla con chi, e il traffico per dispositivo e il rilevamento delle intrusioni in senso stretto richiedono i contatori del router o una porta mirror, che è un passo successivo.",
        "bullets": [
            "**Cosa c'è in rete:** la tabella dei vicini della macchina, un tocco a ogni indirizzo perché si riempia, un'eco a ogni dispositivo trovato (latenza e TTL) e ciò che i dispositivi annunciano di sé (mDNS, UPnP, NetBIOS, DNS inverso). Per ciascuno: indirizzo, MAC, produttore (dal registro IEEE, 40.000 blocchi), nome, tipo, sistema, porte aperte con ciò che dice ognuna e quando è stato visto la prima e l'ultima volta.",
            "**Porte:** una connessione TCP a 17 (o 44) porte di ogni dispositivo, dodici alla volta, leggendo al più poche centinaia di byte della risposta; mai un accesso, mai un exploit. Un dispositivo nuovo si guarda subito, gli altri ogni quarto d'ora.",
            "**Cosa cambia:** un dispositivo che compare (la prima scansione impara soltanto), tace o torna, cambia indirizzo, una porta che si apre o si chiude, e due macchine che rispondono per lo stesso indirizzo (soprattutto quello del router). Ogni evento ha un id, quindi si dice una volta sola.",
            "**Internet:** ogni pochi secondi un'eco al router, una connessione TCP, due domande DNS a risolutori scelti e una pagina web. Un'interruzione richiede tre giri per chiamarsi così e due per dirsi finita, si data dal primo giro fallito e si conta fino al primo buono, e dice di chi è la colpa: del gestore (il router risponde e nulla oltre) o di questa parte (anche il router non risponde). Latenza, perdita e le interruzioni delle ultime 24 ore.",
            "**Guarda solo la tua rete:** rifiuta ogni indirizzo non privato (10/8, 172.16/12, 192.168/16) e ogni intervallo più grande di un /22; un elenco di esclusione lo tiene lontano da ciò che è fragile; a un dispositivo non si invia nulla che non sia una domanda.",
            "**Il messaggio** `armor/network/<nodo>/state`: l'interfaccia, internet, ogni dispositivo e gli ultimi eventi; è nel contratto condiviso (330 vettori) e porta rilevazioni, mai comandi. `python -m armor_network scan` lo stampa come tabella, `watch` informa ARMOR-SERVER, `demo` recita una casa inventata (si unisce un dispositivo nuovo, una telecamera apre Telnet, internet cade e torna, qualcuno risponde per il router) senza toccare alcuna rete.",
            "**Dove si vede:** il menu Rete di ARMOR-STUDIO (i dispositivi, internet con le sue interruzioni e la latenza, il traffico e gli eventi; un amministratore dà un nome ai dispositivi e segna quelli noti, ciò che spegne l'allarme di un dispositivo nuovo), il Progettista di rete (il disegno della rete di casa, confrontato con ciò che è stato trovato e capace di disegnarlo) e la schermata Rete dell'app Android. ARMOR-SERVER genera gli allarmi.",
            "**Non ancora:** i contatori del router stesso (traffico per dispositivo), la cattura dei pacchetti, controllare qualcosa (bloccare un dispositivo, chiudere una porta, cambiare il router) e settimane su una rete reale.",
        ],
        "note": "Vedi il [progetto](docs/DESIGN.md), le [note di sicurezza](docs/SAFETY.md), l'[uso](docs/USAGE.md) e i [messaggi](docs/MESSAGES.md).",
    },
    "ARMOR-SIMULATOR": {
        "tagline": "Simulatore di telemetria offline con guasti ripetibili",
        "honest": "Gli scenari, i guasti, l'invio a un server e i 28 test sono reali. La geometria è **illustrativa**, non un modello del vero radar LD2450, e nulla è stato confrontato con hardware reale.",
        "bullets": [
            "**Scenari:** `patrol`, `crossing`, `two-intruders` ed `empty`, su una geometria d'angolo a tre sensori, con un ciclo di luce giorno/notte o una notte fissa.",
            "**Guasti ripetibili:** un nodo muto, messaggi fuori ordine o duplicati, un nodo instabile e messaggi volutamente non validi (lux oltre il limite, campo sconosciuto, troppe tracce) per i test negativi.",
            "**Deterministico:** lo stesso seme stampa sempre le stesse righe; non viene inviato nulla senza `--server-url` e `--ingest-token`.",
            "**Verificato contro il contratto:** `--validate` fa passare ogni messaggio per ARMOR-COMMON prima di emetterlo.",
            "**Invio prudente:** si accetta solo un'origine http(s) semplice; un 4xx ferma l'esecuzione, un 5xx o un errore di rete viene ritentato.",
            "**Nodo elettrico:** `--electrical` aggiunge i tre canali di un nodo elettrico (l'ingresso di rete, uno scaldabagno e un bus in continua) su una giornata accelerata, con un'interruzione di rete, un periodo di tensione alta e un allarme di contatore.",
            "**Impianto solare:** `--solar` aggiunge un inverter e un pacco batterie da due moduli (quindici celle ciascuno, con le capacità) su un giorno accelerato di 240 campioni, con un'interruzione di rete a fine giornata; i messaggi sono verificati contro il contratto solare di ARMOR-COMMON e consegnati a `/api/v1/solar`.",
        ],
        "note": "Tutte le opzioni, gli scenari e i guasti: [uso](docs/USAGE.md).",
    },
    "ARMOR-SERVER-AI": {
        "tagline": "Politica di inferenza visiva: decide e spiega, senza mai agire",
        "honest": "Il livello decisionale è reale e testato (26 test). **Qui nulla fa ancora girare una telecamera, RTSP o TensorRT**: serve il Jetson, e non è provato.",
        "bullets": [
            "**Profilo giorno/notte con isteresi:** poca luce sotto i 30 lux, ritorno al giorno solo sopra i 60 lux e mai due volte entro 30 s, così il crepuscolo non lo fa oscillare.",
            "**Fusione spiegabile:** ogni rilevamento e le tracce radar danno una gravità (`ignore`, `review`, `high`) con i motivi. Una persona vista all'80 % o più **e** una traccia radar danno `high`; la poca luce abbassa solo la soglia di revisione; un rilevamento più vecchio di 10 s è ignorato.",
            "**Solo raccomandazioni:** una decisione porta sempre `authorizes_action = false`. Il server centrale autentica e autorizza ogni azione.",
            "**Motori verificati con checksum:** i motori TensorRT precompilati sono accettati solo se presenti, non vuoti e, con un `engines.json`, corrispondenti al loro SHA-256. Non si compila né si scarica nulla.",
            "**Worker JSONL:** risultati numerati e spiegati; una riga errata segnala il proprio numero e non ferma mai il flusso.",
        ],
        "note": "Vedi il [confine dell'inferenza](docs/INFERENCE_BOUNDARY.md).",
    },
    "ARMOR-VOICE-AI": {
        "tagline": "Intenti vocali offline con una conferma che chi chiama non può falsificare",
        "honest": "Le regole degli intenti, la conferma firmata e l'audit sono reali e testati (20 test). **Nessun motore di riconoscimento o sintesi vocale fa ancora parte di questo repository.**",
        "bullets": [
            "**Una lista chiusa:** `status`, `silence`, `arm` e `disarm`, in inglese e spagnolo, dopo aver normalizzato accenti, punteggiatura e formule di cortesia. Tutto il resto, o ciò che è ambiguo, non viene capito.",
            "**Una conferma emessa dal servizio:** `arm` e `disarm` restituiscono un token firmato al primo turno e sono accettati solo se un turno successivo lo rimanda per lo stesso intento entro 30 s. Non si può falsificare, reindirizzare, riutilizzare né sostituire con un semplice `confirmed: true` (rifiutato).",
            "**Decisioni, non audio:** con `--audit-file` ogni decisione registra l'intento, l'esito e uno SHA-256 della trascrizione, mai l'audio né le parole grezze.",
            "**Solo raccomandazioni:** un comando accettato viene passato ad ARMOR-SERVER, che lo autentica e lo autorizza comunque.",
        ],
        "note": "Vedi la [sicurezza vocale](docs/SAFETY.md).",
    },
    "ARMOR-ELECTRICAL": {
        "tagline": "Nodo elettrico: legge tensioni, correnti, potenza ed energia della rete AC e DC della casa e custodisce le regole per manovrarla (nucleo testato sul PC e un firmware che compila; non ha mai girato su una scheda)",
        "honest": "**Maturità: scaffolding.** Il nucleo (i frame dei contatori PZEM-004T v3 e PZEM-017, il bus che li interroga, il messaggio del nodo e le regole di manovra: 53 controlli dei contatori e 135.736 delle regole di manovra) è testato su un computer con contatori e contattori simulati, e i messaggi che produce sono accettati da ARMOR-COMMON. Il firmware del nodo (le impostazioni, la linea seriale e le pagine Contatori e Letture del suo pannello: 71 controlli in più) compila nel container ESP-IDF 5.4.2 per le due schede. **Non ha mai girato su una scheda, nulla è stato collegato a un contatore o a un contattore, e nulla qui comanda niente.**",
        "bullets": [
            "**Lettura dei contatori:** i frame Modbus RTU dei **PZEM-004T v3** (AC) e **PZEM-017** (DC) di Peacefair: il CRC, la richiesta che legge i registri e la decodifica della risposta (tensione, corrente, potenza, energia, frequenza, fattore di potenza, allarme). Si costruisce solo la richiesta di lettura: quelle che scrivono in un contatore (indirizzo, soglie, azzeramento dell'energia) non si costruiscono da nessuna parte. Una risposta che non torna, o con un valore che nessun contatore reale potrebbe dare, viene rifiutata.",
            "**Il bus:** una linea con più contatori si interroga uno alla volta, con un timeout; si conserva l'ultima lettura buona di ciascuno e un contatore che tace non viene più pubblicato dopo dieci secondi.",
            "**Il messaggio** `armor/electrical/<nodo>/state`: una voce per canale (un circuito, una linea, l'ingresso di rete, un bus DC) con AC o DC, tensione, corrente, potenza, energia, frequenza, fattore di potenza, lo stato di un interruttore come lo vede il nodo e un allarme; è nel contratto condiviso e porta uno stato, mai un comando.",
            "**Le regole di manovra,** a prescindere da qualsiasi hardware: un controllore dello scambio tra due sorgenti che non comanda mai entrambe, richiede la manovra consentita, il nodo armato poco prima e i due contattori confermati aperti per tutto il tempo morto, e trasforma un contattore che non mostra ciò che gli è stato ordinato in un guasto che resta finché non viene riconosciuto. **La manovra è disattivata per impostazione predefinita e nulla pilota alcun hardware.**",
            "**I comandi a un commutatore, non attivati:** il messaggio di stato può portare lo stato dei commutatori del nodo, e il contratto condiviso ha un comando (`arm`, poi `close_a` o `close_b` con un token monouso, `open`, `acknowledge`) e la risposta del nodo; il nucleo li legge e risponde con le regole sopra, provato con i vettori condivisi e con contattori simulati. Nessuna immagine del firmware lo include, quindi nulla può azionare un contattore, e ARMOR-SERVER rifiuta di inviare un comando se non è stato attivato (`ARMOR_ELECTRICAL_SWITCHING=1`) e l'ACL del broker non lo consente.",
            "**Dove si vede:** il *Progettista elettrico* di ARMOR-STUDIO disegna la rete della casa e mostra su ogni elemento ciò che misura il suo canale; ARMOR-SERVER conserva le letture, la loro cronologia e le somme.",
            "**Il firmware del nodo** (ESP32-S3-WROOM-1 N16R8 in Wi-Fi, o la Waveshare ESP32-S3-ETH sul suo cavo): le impostazioni, una linea seriale per fino a sedici contatori e il pannello web degli altri nodi (messa in servizio, utenti, Wi-Fi, broker, aggiornamento via etere, HTTPS) con le sue pagine Contatori e Letture, in sette lingue. Legge soltanto: le regole di manovra non sono collegate. Vedi [il firmware](docs/NODE_FIRMWARE.md).",
            "**Configurazione dal telefono via Bluetooth,** lo stesso canale del nodo radar: l'app ARMOR trova il nodo come `ARMOR-XXXXXX` e ne imposta nome, Wi-Fi, indirizzo, broker e modo Bluetooth con gli utenti e il codice di messa in servizio del pannello ([il protocollo](docs/BLE_PROVISIONING.md)). Ascolta solo finché il nodo non ha utenti, salvo diversa impostazione. La parte radio non ha mai girato su una scheda.",
            "**Non ancora:** il firmware in funzione su una scheda, l'hardware, qualsiasi misura di un impianto reale e qualsiasi manovra.",
        ],
        "note": "Vedi il [progetto](docs/DESIGN.md), le [note di sicurezza](docs/SAFETY.md), le [regole di manovra](docs/SWITCHING.md), i [protocolli](docs/PROTOCOLS.md) e i [messaggi](docs/ELECTRICAL_MESSAGES.md).",
    },
    "ARMOR-SOLAR": {
        "tagline": "Nodo gateway solare: legge inverter e batterie da fino a dieci porte seriali (firmware ESP32-S3, il suo pannello web e la libreria dei protocolli)",
        "honest": "**Maturità: scaffolding.** Il firmware si compila nel container ESP-IDF 5.4.2, il suo nucleo (le impostazioni, lo scambio con ogni tipo di dispositivo, l'aritmetica dell'UART emulata: 2,548 controlli) è testato su computer con dispositivi simulati, i messaggi che produce sono accettati da ARMOR-COMMON e il pannello è stato provato in un browser contro un nodo simulato. **Non ha mai girato su una scheda e nessun inverter o batteria è stato collegato**: il Wi-Fi, il pannello con TLS, l'aggiornamento, le UART hardware ed emulate e i formati dei protocolli (scritti da documenti pubblici e a memoria) non sono mai stati provati. I frame ANT-BMS dei test sono stati catturati da altri sui loro apparecchi: questo progetto non ne ha letto nessuno di persona.",
        "bullets": [
            "**Due schede, un solo firmware:** una ESP32-S3-WROOM-1 N16R8 via Wi-Fi (predefinita) e la Waveshare ESP32-S3-ETH sul suo cavo Ethernet (DHCP o indirizzo fisso; tiene la propria rete Wi-Fi per raggiungerla da un telefono). L'immagine si sceglie in compilazione (`tools/build_node.sh generic s3-wifi` o `generic s3-eth`); la tabella dei pin, i pin predefiniti delle porte e l'accesso seguono la scheda, e un'immagine vale solo per la sua scheda. Entrambe compilano e sono testate sul computer; nessuna ha girato su una scheda.",
            "**Il firmware del nodo** (ESP32-S3-WROOM-1 N16R8 via Wi-Fi, o Waveshare ESP32-S3-ETH via cavo): dieci porte seriali, tre UART hardware e sette emulate (fino a 19200 baud), ognuna indipendente e ognuna legge un inverter, una batteria o un monitor grezzo, così un nodo può leggere solo inverter, solo batterie o un misto.",
            "**Il pannello web del nodo,** lo stesso dei nodi radar: configurazione con un codice mostrato sulla console USB, accesso e utenti, Wi-Fi (stazione e punto di accesso), broker, aggiornamento via radio con ripristino, registro, HTTPS, e le pagine delle porte (con ciò che ognuna sente, per protocolli non ancora decodificati) e delle letture, in sette lingue.",
            "**Inverter Voltronic / MPP Solar** (Axpert, PIP, InfiniSolar e cloni), RS232 a 2400 baud: i frame e il loro CRC, e le letture `QPIGS` (rete, uscita, batteria, FV, bit di stato), `QMOD` (modo), `QPIWS` (avvisi e guasti per nome) e `QPIRI` (valori nominali). Si possono costruire solo comandi di lettura: un'impostazione cambia come viene alimentata la casa. Tre dialetti, scelti sulla porta o trovati da essa (*auto*): PI30, REVO (un altro `QPIGS`, risposte con checksum) e PI18 (`^P005GS`: InfiniSolar V, LV5048, SunGoldPower), sola lettura.",
            "**Batterie Pylontech** (US2000, US3000, US5000): la tabella `pwr` della console (tensione, corrente, temperature e stato di carica di ogni modulo), `bat <n>` (tensione e temperatura di ogni cella) e `info <n>` (modello, capacità residua e totale, cicli), riassunte come un unico pacco con capacità ed energia totali, e il frame RS485 con i suoi due controlli. I formati sono scritti a memoria dalla console pubblica e possono variare tra i firmware. Le colonne si trovano dai nomi dell'intestazione (anche il formato della US5000 V2.3 con le colonne Id, MosTempr e SysAlarm.St), la carica residua e il bilanciamento vengono da `bat`, e modello, capacità nominale e cicli da `info` e `stat`, richiesti una volta e conservati mezz'ora.",
            "**I messaggi del nodo** (`armor/solar/<nodo>/<dispositivo>/state`, uno per inverter o pacco di batterie), definiti in ARMOR-COMMON con schemi e vettori di conformità; ciò che producono le porte è verificato contro di essi.",
            "**Batterie ANT-BMS** (le schede nere dei pacchi autocostruiti, da 7S a 32S), UART a 3,3 V a 19200 baud: entrambi i protocolli del suo firmware (il nodo chiede nell'uno e poi nell'altro e resta con quello che risponde), con celle, temperature, stato di carica, corrente, capacità e stati dei MOSFET e del bilanciatore, verificati su frame catturati su quattro modelli reali. Solo lettura: i suoi comandi di scrittura possono scollegare una batteria sotto carico. Un pulsante della pagina delle porte legge anche modello, versione e le 56 impostazioni di protezione e bilanciamento del BMS (protocollo nuovo), in sola lettura.",
            "**Configurazione dal telefono via Bluetooth,** lo stesso canale del nodo radar: l'app ARMOR trova il nodo come `ARMOR-XXXXXX` e ne imposta nome, Wi-Fi, indirizzo, broker e modo Bluetooth con gli utenti e il codice di messa in servizio del pannello ([il protocollo](docs/BLE_PROVISIONING.md)). Ascolta solo finché il nodo non ha utenti, salvo diversa impostazione. La parte radio non ha mai girato su una scheda.",
            "**La scheda base con multiplexer (il profilo *mux*):** tre UART hardware, ciascuna dietro un 74HC4052, servono fino a otto porte in gruppi da 4, 2 e 2 che si alternano sulla loro linea, ogni porta con la propria velocità e polarità, e un LED per porta tramite un 74HC595; le celle di una pila Pylontech alta si possono leggere a rotazione. Per un inverter nel dialetto standard, il **secondo ingresso fotovoltaico** (`QPIGS2`) e le **unità di un sistema in parallelo** (`QPGS`) sono letture facoltative. Nulla di tutto ciò ha mai girato su una scheda.",
            "**Non ancora:** il collegamento Bluetooth dell'ANT-BMS (il nodo usa il cavo, il più stabile dei due) e una prova su una scheda reale con dispositivi reali.",
        ],
        "note": "Vedi la [guida al firmware](docs/NODE_FIRMWARE.md) (la scheda, le porte, il primo avvio e l'elenco delle prove da banco) e le [note di cablaggio](docs/NODE_HARDWARE.md).",
    },
    "ARMOR-RADAR": {
        "tagline": "Firmware del nodo di campo (Waveshare ESP32-S3-ETH, tre radar o sensori di presenza, Ethernet e Wi-Fi) con un proprio pannello web e il nucleo testato su computer",
        "honest": "**Maturità: scaffolding.** Il nucleo indipendente dall'hardware (859 controlli: i decodificatori dell'LD2450, dell'LD2461 e di quattro sensori di presenza, il canale di comando dell'LD2450, le impostazioni e i loro controlli, la tabella dei pin, utenti e sessioni, la logica dei pin associati, il piano di rete e il serializzatore dei messaggi, il cui output è accettato da ARMOR-COMMON) è testato su computer, il **pannello web** è stato provato in un vero browser contro un nodo finto e l'**immagine del firmware si compila** nel container ESP-IDF 5.4.2. **Non ha mai girato su una scheda**: nessun frame è stato catturato da un modulo reale, il codice di Ethernet, ponte Wi-Fi, sensore di luce e aggiornamento non è mai stato provato, il canale di comando dei radar non è verificato né sul documento del produttore né su un modulo, il certificato HTTPS del pannello è creato dal nodo stesso e mai provato in un vero browser, e i decodificatori dell'LD2461 e dei sensori di presenza corrispondono solo agli esempi dei loro manuali, senza un modulo reale.",
        "bullets": [
            "**Due schede, un solo firmware:** la Waveshare ESP32-S3-ETH (Ethernet, predefinita) e una ESP32-S3-WROOM-1 N16R8 senza Ethernet (solo Wi-Fi: la configurazione chiede la rete Wi-Fi a cui unirsi e il nodo tiene sempre la propria rete). L'immagine si sceglie in compilazione (`tools/build_node.sh generic s3-eth` o `generic s3-wifi`); la tabella dei pin e l'accesso seguono la scheda, il pannello nasconde ciò che la scheda non ha e un'immagine vale solo per la sua scheda. Entrambe compilano e sono testate sul computer; nessuna ha girato su una scheda.",
            "**Due nodi da 270 gradi:** ogni Waveshare ESP32-S3-ETH legge fino a tre radar LD2450 sulle sue tre UART, montati a 75 gradi l'uno dall'altro, via Ethernet cablata (W5500) con DHCP o indirizzo fisso, alimentato con PoE o USB. *Add a 270° node* di Studio crea i tre radar già associati al nodo.",
            "**Un pannello web su ogni nodo,** con l'aspetto di Studio e in sette lingue, incorporato nel firmware: panoramica, rete, Wi-Fi, broker, radar, pin, utenti, aggiornamento del firmware e registro. Un nodo senza utenti apre il Wi-Fi `ARMOR-SETUP-xxxxxx` e crea il suo primo amministratore con un codice di configurazione; le password sono PBKDF2 con sale, le sessioni sono token casuali e ogni impostazione è nella flash del nodo, quindi un'unica immagine serve tutti i nodi e nessuna password è compilata ([il pannello](docs/NODE_PANEL.md)).",
            "**Un solo Wi-Fi da più nodi:** ogni nodo può offrire un access point collegato alla sua porta Ethernet; con lo stesso nome e password e il canale in automatico (1, 6 o 11 secondo la MAC), telefoni e sensori Wi-Fi vedono una sola rete con un solo server DHCP. Non è una rete mesh radio: ogni nodo mantiene il suo cavo. Un nodo può invece unirsi al Wi-Fi di un router (con ricerca delle reti), e uno senza cavo può essere configurato via **Bluetooth** dall'app Android.",
            "**Pin per il server:** qualsiasi pin libero diventa un ingresso, un'uscita (con uno stato sicuro se il broker si perde), PWM o una lettura analogica, e appare come dispositivo del server: un relè o un contatto non richiede un nuovo firmware. I pin riservati della scheda non vengono mai offerti.",
            "**Aggiornamenti via radio (OTA) con ripristino** dal pannello (due slot sulla flash da 16 MB) e un **collegamento da Studio** al pannello di ogni nodo, dall'indirizzo che il nodo pubblica.",
            "**Il pannello in HTTPS:** il nodo crea il proprio certificato (autofirmato, conservato in flash) e serve il pannello sulla porta 443 oltre che sulla 80, o solo sulla 443; il cookie di sessione è marcato Secure e l'impronta del certificato viene mostrata per confrontarla con l'avviso del browser. **Identità di traccia stabili:** i bersagli di ogni frame sono associati a quelli seguiti prima, così una persona mantiene lo stesso id, un frame perso non fa sfarfallare e le posizioni sono un po' levigate.",
            "**Sei modelli di sensore, uno per porta:** una porta porta un LD2450 o un LD2461 (tracker che alimentano il perimetro, con il campo proprio del modello in Studio) o un sensore di presenza (LD2410, LD2412, LD2410S, MR24HPC1) che diventa un dispositivo del server e pubblica presenza e distanza. Si sceglie nel pannello; cos'è ciascuno, il suo protocollo e cosa non è stato verificato sono in `docs/SENSORS.md`.",
            "**Decodificatore, salute e configurazione dell'LD2450:** un framer che si risincronizza trova i frame in un flusso rumoroso; ogni frame da 30 byte dà fino a tre bersagli che diventano tracce del contratto; la console e il pannello dicono per radar se trasmette, tace o manda dati illeggibili. Il pannello può anche leggere la versione del modulo, scegliere uno o tre bersagli e impostare zone di rilevamento (un protocollo non verificato su un modulo).",
            "**Luce ambiente e messaggi esatti rispetto al contratto:** il VEML7700 con range automatico; JSON di telemetria, salute e informazioni che segue gli schemi pubblicati e rifiuta di scrivere qualsiasi cosa non valida, con timestamp di orologio reale (SNTP) e un last will MQTT. La telemetria è trattenuta finché nessun radar trasmette, mai un «tutto tranquillo» vuoto.",
            "**Un'immagine per tutte le schede, come un prodotto di rete:** il firmware è lo stesso e la MAC distingue le schede (`armor-` e sei cifre finché non ricevono un nome); `adopt_node.py` dà a un nodo appena flashato il suo amministratore, la sua identità di broker e le impostazioni comuni della flotta via rete, con un codice di configurazione calcolato dalla sua MAC: 5 nodi o 27 sono lo stesso lavoro. **Strumenti da banco:** flash via USB-C, un nodo finto per lavorare sul pannello e un convertitore da un registro di frame grezzi a un fixture di test ([messa in servizio da banco](docs/BENCH_BRINGUP.md)).",
        ],
        "note": "I test su computer richiedono un compilatore C++17 (Linux, WSL, MSYS2). Vedi la [messa in servizio da banco](docs/BENCH_BRINGUP.md), il [pannello](docs/NODE_PANEL.md) e il [confine hardware](docs/HARDWARE_BOUNDARY.md).",
    },
    "ARMOR-ANDROID-CONTROL": {
        "tagline": "Client mobile dell'operatore per ARMOR-SERVER",
        "honest": "Le regole di sicurezza degli indirizzi e di decisione degli allarmi hanno test unitari (55) e l'app si compila. **Non è stata eseguita su un telefono contro il server**, quindi il flusso di permesso delle notifiche e il servizio in background non sono verificati. Armo, allarmi e dispositivi seguono le rotte del server ma non sono stati provati su un telefono reale.",
        "bullets": [
            "**Accesso con le credenziali del server:** IP, porta, utente e password; la password crea una sessione HttpOnly e non viene mai salvata sul telefono.",
            "**Monitor delle telecamere:** da 1 a 16 riquadri, una vista ingrandita, MJPEG dal vivo che mantiene le proporzioni, un joystick PTZ limitato, istantanee e registrazioni.",
            "**Inserire e disinserire,** dopo una conferma; **allarmi** da riconoscere, con un badge per quelli in attesa; **dispositivi** (fumo, gas, allagamento, porta, finestra, movimento, clima, prese, luci, sirene, serrature) con il loro stato e On / Off / Inverti.",
            "**Radar dal vivo, in 2D e 3D:** la scheda Radar disegna il sito come progettato in Studio (terreno, edifici, alberi, pali, campi dei radar e delle telecamere) e le persone che i radar vedono muoversi, aggiornato ogni secondo e mezzo; trascina, pizzica e ruota la vista 3D. Il posizionamento segue le regole di Studio, ma non ha mai mostrato un radar reale.",
            "**Solare:** una voce in *Más* (e un riquadro nello Stato) mostra i totali (sole, consumo, batterie con carica e flusso, se c'è la rete) e ogni inverter e batteria che il server segnala: i loro valori, le celle di una batteria a richiesta con la più alta e la più bassa evidenziate, gli apparecchi che aspettano ancora dati e un contrassegno su una lettura di esempio o un apparecchio muto. Aggiornato ogni cinque secondi quando è aperta; provata sulle forme di risposta del server e in un emulatore contro un server locale con letture di esempio, mai con apparecchi reali. Gli allarmi solari (guasto di un inverter, batteria scarica o in protezione, apparecchio muto) svegliano il telefono come quelli di un dispositivo.",
            "**Configurare un nodo di campo via Bluetooth** (dalla schermata di accesso o da *Más > Configurar un nodo*): trova i nodi che annunciano `ARMOR-xxxxxx`, crea l'amministratore di uno nuovo o accede, cerca reti Wi-Fi e imposta il nome del nodo, il Wi-Fi di un router o un indirizzo fisso e il broker, per i nodi senza cavo Ethernet. Compilato e testato in unità, mai eseguito contro un nodo né un telefono.",
            "**Libreria delle prove,** stato del perimetro e dei nodi, e **cronologia** di ogni avviso, nodo, telecamera, dispositivo, allarme e cambio di modo.",
            "**Notifiche di allarme** per un nodo che raggiunge HIGH, una telecamera che non risponde più, un allarme di dispositivo (fumo, gas, allagamento, panico sempre; una porta, finestra o un sensore di movimento a sistema inserito) e, a sistema inserito, un nodo che va offline; un controllo opzionale in background usa la sessione corrente e lo dice quando finisce.",
            "**Attenzione con la password:** l'HTTP semplice è ammesso solo verso un *letterale* IPv4 di rete privata o loopback. Un nome host che inizia soltanto come un indirizzo privato (`10.attacker.example`) o un indirizzo con uno zero iniziale (alcuni resolver leggono `010.0.0.1` come il pubblico `8.0.0.1`) viene rifiutato.",
            "**Rete elettrica:** una voce in *Altro* (e una tessera nella schermata di stato) mostra la potenza dell'ingresso di rete (in prelievo o in immissione), ogni canale che i nodi elettrici misurano (tensione, corrente, potenza, energia, frequenza, fattore di potenza, lo stato di un interruttore) e gli allarmi dei contatori; gli allarmi dei nodi elettrici (quello di un contatore, la tensione di rete fuori intervallo, la rete mancante, un nodo che non risponde più) svegliano l'operatore come quelli solari. La scheda di un inverter mostra anche il secondo ingresso fotovoltaico e le unità di un sistema in parallelo.",
            "**Un aspetto fatto di icone:** superfici quasi nere, accento ciano, ambra per l'attenzione, icone grandi con poche parole, barra inferiore, una pagina Informazioni e un pulsante di uscita.",
        ],
        "note": "L'APK di debug non è firmato per la distribuzione. Vedi il [confine del client](docs/CLIENT_BOUNDARY.md).",
    },
    "ARMOR-HARDWARE": {
        "tagline": "Contenitori, elettronica e matrice di accettazione da banco",
        "honest": "Il contenitore è un **punto di partenza meccanico stampabile, non una certificazione IP, RF o termica.** Nulla è stato misurato su un prototipo; ogni riga della [matrice di accettazione da banco](docs/BENCH_ACCEPTANCE.md) è *non testata*.",
        "bullets": [
            "**Il vero progetto è `CAD/CARCASA_SENSORES.scad`** (con esportazioni STL, 3MF e AMF): una base d'angolo a 90 gradi con visiera, tetto e fondo, gradini di ritegno, un coperchio frontale scorrevole da 2 mm e alette laterali, tutto guidato da parametri con nome. `scad/node_enclosure.scad` è solo una scatola provvisoria.",
            "**Volumi riservati** per tre moduli radar, la scheda ESP32-S3-ETH-PoE, la finestra del sensore, un passacavo, la magnetica PoE e il riscaldatore PTC. Nessun materiale metallico, conduttivo o caricato di carbonio davanti a un'apertura a 24 GHz senza attenuazione misurata.",
            "**Matrice di accettazione da banco:** i controlli di radio, ambiente, alimentazione, rete e telecamera, ciascuno con un metodo e un criterio di superamento proposto, e una tabella di compatibilità delle telecamere da compilare.",
            "Prima della fabbricazione, registrare i contorni esatti delle schede, i connettori, la posizione delle viti, le aree di esclusione delle antenne, il percorso termico e l'obiettivo di tenuta ([dati di progetto](docs/DESIGN_INPUTS.md)).",
        ],
        "note": "Vedi il [confine di validazione](docs/VALIDATION.md). La licenza hardware prevista è CERN-OHL-S-2.0; aggiungi il testo completo prima di pubblicare i progetti.",
    },
    "ARMOR-DEVOPS": {
        "tagline": "Topologia di distribuzione e banco di prova CM5 isolato",
        "honest": "L'installatore del banco CM5 è stato eseguito su una vera CM5 che ospita altro software, rimasto in salute. La topologia Docker Compose e il suo profilo TLS opzionale sono stati costruiti ed eseguiti davvero con Docker Engine in WSL (`scripts/test_compose.sh`, 12 controlli, che hanno trovato e corretto tre difetti), ma **non sul Jetson**. Gli script di backup e ripristino hanno un test di andata e ritorno superato.",
        "bullets": [
            "**Un firewall della macchina centrale** (`scripts/firewall_core.sh`): la porta del broker solo dalla rete di campo, quelle del server e di Studio solo dalla rete dei client (se indicata), in una tabella propria che non nomina altro e accetta il resto; `apply --rollback-after` toglie di nuovo le regole se non le confermi, così un errore non ti chiude fuori. Le regole e i rifiuti sono testati (36 controlli, non si carica nulla); non è stato caricato su nessuna macchina e le VLAN restano un progetto per router e switch.",
            "**Banco di prova CM5:** `scripts/deploy_cm5.sh` costruisce in una copia pulita, invia un archivio ed esegue `scripts/install_cm5.sh`, che crea un proprio utente, una propria cartella e due unità systemd su porte proprie (tre con `--with-mqtt`: il Mosquitto proprio di A.R.M.O.R. sulla porta 18883, verificato su una vera CM5), con limiti di risorse, e non tocca mai un altro progetto ([dettagli](docs/CM5_TEST_BENCH.md)).",
            "**Topologia Compose:** un broker Mosquitto non anonimo con un'identità per nodo, il server e Studio dietro un nginx che inoltra `/api/`; solo Studio è pubblicato, sul loopback. Container rinforzati, una rete interna per il nucleo e volumi con nome per lo stato.",
            "**Dispositivi e letture sul broker del banco:** il server può ascoltare e comandare `armor/device/#` e leggere `armor/node/+/info`, `armor/solar/#` e `armor/electrical/#`; `scripts/mqtt_identity.sh add device NAME` dà a un dispositivo i propri topic e `add bridge NAME` a un bridge Zigbee2MQTT o Shelly tutti. `scripts/mqtt_identity.sh electrical-switching NODE_ID on` è l'unica cosa che permette al server di comandare il commutatore di un nodo elettrico (disattivato per impostazione predefinita; `off` lo toglie).",
            "**Segreti:** `scripts/generate_secrets.sh` crea segreti casuali senza stamparne nessuno; `scripts/check-required-env.sh` rifiuta valori mancanti, di esempio, corti o ripetuti.",
            "**Backup e ripristino:** `scripts/backup_data.sh` crea un archivio cifrato AES-256, verificato e con checksum dei dati del server (senza le prove salvo richiesta); `scripts/restore_data.sh` lo elenca o lo ripristina senza mai sovrascrivere dati esistenti. La chiave delle telecamere volutamente **non** è nell'archivio.",
            "**TLS:** un profilo Compose `tls` opzionale mette Caddy, con una propria autorità di certificazione locale, davanti a Studio ([dettagli](docs/BACKUP_AND_TLS.md)).",
        ],
        "note": "Vedi il [confine di distribuzione](docs/DEPLOYMENT_BOUNDARY.md).",
    },
    "ARMOR-SERVER": {
        "tagline": "Coordinatore centrale di sicurezza: ingresso della telemetria, allarmi, dispositivi, letture solari e gateway delle telecamere",
        "honest": "Ogni rotta, sessione, cifratura e regola delle prove qui sotto è reale e coperta da test (`npm test`, 168 test, con una suite di integrazione HTTP completa contro un server isolato). Ha funzionato con un vero broker MQTT sulla CM5 (con script, non con il firmware di un nodo di campo), ha trasmesso video dal vivo, salvato un'istantanea e registrato da cinque vere telecamere IP tramite FFmpeg. Ciò che **non è ancora provato**: ONVIF con una vera telecamera ONVIF, il PTZ su ogni firmware di telecamera (funziona sull'unità Hi3510), qualunque hardware Jetson e le rotte solari con un vero nodo gateway (sono testate con letture generate).",
        "intro": "**ARMOR-SERVER** è il centro di fiducia di A.R.M.O.R. I nodi di campo pubblicano osservazioni di radar, luce e salute; questo servizio le valida, conserva l'ultimo stato noto di ogni nodo e lo serve alla console Studio e al client Android. Possiede anche tutto ciò che tocca una telecamera, così **nessun browser né telefono detiene mai una password di telecamera o un indirizzo RTSP**.",
        "bullets": [
            "**Ingresso validato:** le osservazioni HTTP e MQTT sono controllate al confine (identificatore, timestamp, intervallo di lux, al massimo 15 tracce) prima di raggiungere la proiezione di stato.",
            "**Stato onesto dei nodi:** un nodo che smette di parlare è mostrato come *obsoleto* e poi *offline* dopo una finestra configurabile, mai online su dati vecchi. Disinserire cancella subito un avviso alto.",
            "**Gateway delle telecamere:** cassaforte di telecamere cifrata, PTZ ONVIF / Hi3510 / PSIA, scoperta dei percorsi RTSP, un relay FFmpeg condiviso per telecamera, istantanee e registrazione MP4, e un watchdog che trasforma una telecamera muta in un evento e, a sistema inserito, in un allarme.",
            "**Libreria delle prove:** conservazione per età e dimensione partendo dalle più vecchie, **prove protette** mai eliminate e uno SHA-256 per la catena di custodia. Una riga di audit per ogni azione rilevante per la sicurezza, senza credenziali.",
            "**Stato che sopravvive:** la modalità di sicurezza e l'ultima osservazione di ogni nodo sono ripristinate dopo un riavvio (un riavvio non disinserisce mai il perimetro in silenzio). Ogni cambio di livello di avviso, di stato del nodo e di modalità resta in una cronologia degli eventi.",
            "**Uscita di allarme:** gli avvisi alti e, a sistema inserito, i nodi muti o offline vanno a MQTT `armor/server/alert` e a un webhook opzionale firmato HMAC; il tempo di permanenza prima di HIGH e le zone ignorate si regolano da Studio.",
            "**Utenti:** nomi e password (hash scrypt), un ruolo `admin` che gestisce gli utenti e un ruolo `operator` che opera; cambiare una password o un ruolo chiude le altre sessioni di quell'utente.",
            "**Dispositivi, allarmi e automazioni:** dispositivi di fumo, gas, allagamento, porta, finestra, movimento, clima, presa, luce, sirena e serratura via MQTT o invio autenticato, con stato normalizzato, disponibilità e comandi; allarmi con ciclo generato / riconosciuto / cancellato; regole che comandano dispositivi quando succede qualcosa; inserire e disinserire da una sessione aperta; e il progetto del sito conservato sul server per tutti i client.",
            "**Letture solari:** inverter e pacchi di batterie (con ogni cella e le capacità) arrivano via HTTP o MQTT, sono validati dal contratto condiviso, conservati con una cronologia (un campione ogni 30 s per un giorno) e totali, segnati come obsoleti dopo due minuti, e generano quattro allarmi (guasto dell'inverter, batteria scarica, allarme della batteria, dispositivo muto).",
        ],
        "sections": [
            {"title": "Modello di sicurezza", "bullets": [
                "Quattro segreti separati: **ingestione** (invio di telemetria, salute e letture solari), **controllo** (inserire / disinserire, eventi), **operatore** (automazione) e **accesso a Studio**; ciascuno è confrontato a tempo costante e nessuno sostituisce un altro.",
                "Ogni rotta che configura, muove, cattura, registra, protegge o elimina richiede un operatore. Il video dal vivo richiede un operatore o un ticket di flusso di breve durata legato a una telecamera.",
                "Le password delle telecamere vivono solo in `data/cameras.json`, cifrate con AES-256-GCM, e nessuna API le restituisce; gli indirizzi ONVIF devono restare sull'host della telecamera e i reindirizzamenti sono rifiutati.",
                "Le sessioni di Studio sono HttpOnly e SameSite=Strict per 8 ore, l'accesso ha un limite di frequenza e gli errori non portano mai una traccia dello stack.",
                "Il server ascolta su 127.0.0.1 a meno che `ARMOR_HOST` sia impostato di proposito, e allora una password di Studio più corta di 12 caratteri è rifiutata.",
            ]},
            {"title": "API", "bullets": [
                "Pubblica: `GET /healthz`. Per un operatore: stato, informazioni, telecamere, media, cronologia, regole, dispositivi, allarmi, automazioni, progetto del sito e `GET /api/v1/solar` con la sua cronologia.",
                "Per i nodi di campo e i gateway: `POST /api/v1/telemetry`, `/health`, `/solar` e `/electrical/readings` con il token di ingestione, e i topic MQTT `armor/node/#`, `armor/solar/#` e `armor/electrical/#`. Gli eventi raggiungono le console dal WebSocket `/api/v1/events`.",
                "Ogni rotta, la sua regola di accesso e il suo schema sono nel file OpenAPI di [ARMOR-COMMON](../ARMOR-COMMON), e un test verifica che non ne manchi nessuna.",
            ]},
            {"title": "Configurazione", "bullets": [
                "Copia `.env.example` in `.env` (ignorato da Git), oppure lascia che `run.bat` / `run.sh` generi segreti casuali alla prima esecuzione.",
                "Obbligatorie: `ARMOR_INGEST_TOKEN` e `ARMOR_CONTROL_TOKEN` (24 caratteri o più, tutte diverse) e `ARMOR_STUDIO_USERNAME` / `ARMOR_STUDIO_PASSWORD` (il primo amministratore).",
                "Comuni: `ARMOR_HOST` / `ARMOR_PORT`, `ARMOR_DATA_DIR`, `ARMOR_FFMPEG_PATH` (video dal vivo e cattura), `ARMOR_MQTT_URL`, `ARMOR_STUDIO_ORIGIN`, `ARMOR_NODE_STALE_AFTER_S`, `ARMOR_CAMERA_CHECK_S`, `ARMOR_ALERT_DWELL_MS`, `ARMOR_ALERT_WEBHOOK_URL` e `ARMOR_COOKIE_SECURE` (a `1` dietro TLS).",
            ]},
        ],
        "note": "Per installare sul banco di prova CM5 (isolato da ogni altro progetto, con utente e porte proprie) vedi [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-STUDIO": {
        "tagline": "Console di esercizio e progettazione: telecamere, radar, allarmi, energia solare, prove e planimetria del sito",
        "honest": "Studio dialoga con [ARMOR-SERVER](../ARMOR-SERVER) ed è coperto da 203 test unitari (lettura delle impostazioni, unione delle telecamere, aritmetica dei grafici solari, ogni menu mostrato nelle sette lingue, host statico). **Non** sono provati: il video dal vivo e il PTZ con ogni telecamera reale, i menu solari con un vero inverter o batteria, né una revisione formale di accessibilità o usabilità. Finché il server non è raggiungibile, Studio mostra dati dimostrativi e lo dice nella barra superiore.",
        "intro": "**ARMOR-STUDIO** è la console dell'operatore. Non detiene mai una password di telecamera, un indirizzo RTSP o un token: accede al server con nome utente e password, riceve una sessione **HttpOnly** di 8 ore e tutto ciò che è privilegiato passa da quella sessione.",
        "bullets": [
            "**Monitor delle telecamere:** 1, 2, 4, 6, 8, 9, 12 o 16 riquadri che si adattano alla cornice (16:9, tutta la matrice visibile, senza ritagli), una vista ingrandita con joystick PTZ limitato, istantanea e registrazione MP4; una **libreria delle registrazioni** per filtrare, visualizzare, riprodurre, proteggere ed eliminare le prove.",
            "**Allarmi, dispositivi e automazioni:** ciò che richiede una persona adesso con riconoscimento e registro chiuso; dispositivi di fumo, gas, allagamento, porta, finestra, movimento, clima, presa, luce, sirena e serratura via Wi-Fi, Zigbee, Bluetooth o cavo (preimpostazioni per Zigbee2MQTT, Tasmota e Shelly); regole che comandano dispositivi quando succede qualcosa; un grande pulsante inserisci / disinserisci.",
            "**Energia solare:** il menu *Inverter* disegna la casa come un flusso di energia animato (pannelli, rete, inverter, batteria e carico, con trattini più veloci quanta più potenza c'è), indicatori, letture, avvisi in parole e grafici di storico; il menu *Batterie* mostra ogni pacco con un livello di liquido, le sue **capacità** (residua e totale, Ah e kWh, cicli, modello), ogni modulo e **ogni cella** come barra con la sua tensione e la differenza in millivolt, e grafici di carica, tensione, corrente, intervallo delle celle e temperatura.",
            "**Panoramica e sistema:** lo stato del perimetro, un riquadro per parte, una mappa viva del progetto con ogni dispositivo e una pagina di sistema con la traccia di audit per un amministratore.",
            "**Radar:** una mappa dal vivo disegnata dal tuo progetto del sito (terreno, edifici, telecamere, radar e loro copertura) con i bersagli che ogni radar segnala, il loro percorso recente e le zone ignorate; stato dei nodi dal vivo, con i nodi muti mostrati come *obsoleti*; il pannello proprio di ogni nodo è a un clic.",
            "**Progettista del sito:** disegna il terreno (rettangolo o qualsiasi forma, con lunghezze digitate), posiziona edifici di più piani con cinque tipi di tetto, porte e finestre a qualsiasi piano e altezza, lampioni, camini, pannelli solari, antenne, pilastri, pali, strade e sentieri, poi telecamere e radar dove vuoi; una pianta 2D in stile CAD e una vista 3D che puoi orbitare, tagliare piano per piano e modificare; annulla e ripeti.",
            "**Configurazione:** indirizzo del server, telecamere (ONVIF/RTSP), scoperta, utenti (il tuo account e, per un amministratore, l'elenco di utenti, ruoli e password), tema e lingua; un'esportazione portatile del sito **senza credenziali**.",
            "**Sette lingue** (inglese, spagnolo, tedesco, francese, italiano, giapponese, cinese) e undici temi, quello predefinito chiamato *Armor*.",
            "**Dichiara il tuo dispositivo:** nei menu Inverter e Batterie aggiungi ogni inverter o pacco batterie con nome, modello (Voltronic, MPP Solar, Pylontech US2000 / US3000 / US5000, ANT-BMS), collegamento (RS232, RS485, USB, CAN, Wi-Fi) e nodo gateway; attende la prima lettura reale e *Mostra letture di esempio* permette di provare il menu nel frattempo.",
            "**Progettista elettrico:** disegna lo schema elettrico della casa (rete, contatore, protezioni, commutatori, distribuzione, FV, inverter, batterie e carichi, in AC e DC) con porte e cavi, raggruppalo in quadri, collega inverter e batterie ai dispositivi solari letti dal server per vedere i loro valori in tempo reale e lascia che i controlli lo rivedano (due sorgenti su una linea, magnetotermici e cavi rispetto alla corrente, protezioni mancanti, tensioni DC). Il disegno è conservato sul server; è un disegno: per ora nulla comanda o misura.",
        ],
        "sections": [
            {"title": "Modello di sicurezza", "bullets": [
                "**Nessun segreto nel browser.** Le password delle telecamere si digitano una volta, si inviano al server e poi si vedono solo come stato «salvata» mascherato. Le esportazioni del sito omettono nomi utente e indicatori di credenziali.",
                "**Le impostazioni salvate sono input non attendibile.** Sono lette valore per valore: un'origine, un tema, una lingua o una forma non validi vengono scartati, le posizioni limitate e le liste contenute.",
                "**Nessuna richiesta a terzi.** I caratteri sono locali; l'host statico invia `Content-Security-Policy: default-src 'self'` limitata al server configurato, `frame-ancestors 'none'`, `nosniff` e `no-referrer`.",
                "Il video dal vivo si mostra solo tramite un indirizzo di flusso che il server rilascia a un operatore.",
            ]},
        ],
        "note": "`tools/serve.mjs` legge `ARMOR_STUDIO_HOST` (predefinito `127.0.0.1`), `ARMOR_STUDIO_PORT` (`5178`), `ARMOR_STUDIO_DIST` e `ARMOR_SERVER_ORIGIN`. Per installare tutto lo stack sul banco di prova CM5 vedi [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-COMMON": {
        "tagline": "Contratti dei messaggi, validazione e lanciatore di progetti condiviso",
        "honest": "Gli schemi, il validatore Python, i 330 vettori di conformità condivisi, i tipi TypeScript e Kotlin generati e il lanciatore di progetti condiviso sono reali e testati (36 test). Il file Kotlin è generato ma **non ancora usato** da ARMOR-ANDROID-CONTROL, e il comando `set_thresholds` porta un solo campo `sensitivity` perché i veri parametri del radar non sono definiti finché non esiste il firmware.",
        "intro": "**ARMOR-COMMON** possiede il significato di ogni messaggio di A.R.M.O.R. I nodi radar, i nodi gateway solari e il simulatore producono questi messaggi; il server, l'IA visiva e il servizio vocale li consumano. Se due progetti non concordano su un campo, decide questo repository.",
        "bullets": [
            "**Un'unica fonte di verità:** schemi JSON in `src/armor_common/schemas/` per telemetria, salute, comando, informazioni del nodo e i due messaggi solari (inverter, batteria con celle e capacità). I campi sconosciuti sono rifiutati ovunque.",
            "**Un validatore che non può saltare una regola:** interpreta direttamente lo schema e rifiuta uno schema che usa una parola chiave che non implementa.",
            "**Vettori di conformità:** 330 payload accettati e rifiutati eseguiti da ogni implementazione (Python qui, TypeScript in ARMOR-SERVER, i controlli di ARMOR-SOLAR), così una deriva fa fallire la compilazione.",
            "**Client generati:** i tipi TypeScript e Kotlin nascono dagli schemi (`tools/generate_types.py --check` li mantiene aggiornati).",
            "**Contratto HTTP:** `openapi/armor-server-0.2.0.yaml` descrive ogni rotta del server, la sua regola di accesso e il suo schema.",
            "**Lanciatore condiviso:** `tools/armor_project_tool.py` dà a ogni repository della famiglia lo stesso flusso `build`, `build-test` e `run`.",
        ],
        "sections": [],
        "note": "Topic del broker: `armor/node/{node_id}/telemetry | health | command | info`, `armor/solar/{node_id}/{device}/state` e `armor/electrical/{node_id}/state | command | result`. Vedi la [guida ai contratti](docs/CONTRACTS.md). Il lanciatore condiviso crea un `.env` ignorato alla prima esecuzione di ARMOR-SERVER con segreti casuali e una password di amministratore casuale; nulla viene stampato né versionato.",
    },
    "ARMOR-DOCS": {
        "tagline": "Architettura canonica, base di sicurezza e la verità su ciò che è provato",
        "honest": "Questo repository documenta interfacce e procedure che sono state validate, e dice chiaramente ciò che non lo è. Leggi la [matrice delle capacità](docs/CAPABILITY_MATRIX.md) prima di credere che una funzione sia «finita»: indica per ognuna se è stata solo simulata, testata su computer o verificata su hardware reale.",
        "intro": "",
        "bullets": [
            "[Matrice delle capacità](docs/CAPABILITY_MATRIX.md): per ogni capacità, simulata, locale o verificata su hardware?",
            "[Architettura](docs/ARCHITECTURE.md): reti, confini di fiducia, tempo e ordine.",
            "[Base di sicurezza](docs/SECURITY_BASELINE.md): il progetto delle VLAN, ciò che il codice impone e ciò che manca ancora.",
            "[Catalogo dei progetti](docs/PROJECT_CATALOG.md): i dodici repository, le loro versioni e le dipendenze.",
            "[Interfacce](docs/INTERFACES.md): chi produce e consuma ogni interfaccia e dove ci si fida.",
            "[Prima fetta verticale](docs/FIRST_VERTICAL_SLICE.md): cosa dimostra il test dal simulatore alla console e cosa no.",
            "**Strumenti:** `make_readmes.py` scrive il README di ogni repository in sette lingue, `make_brand.py` il suo banner e la sua icona, `publication_check.py` cerca qualsiasi cosa privata prima di una pubblicazione e `clean_history.py` crea una copia pubblicabile di un repository.",
        ],
        "sections": [],
        "note": "Gli audit della famiglia (in spagnolo) si trovano nella radice di questo repository.",
    },
}
