"""Italiano: le parole attorno a ogni README, la descrizione di una riga di ogni repository e il testo di tutti i repository.

Copyright (C) 2026 JuanenRac (Electro Hobby 3D). GPL-3.0-or-later.
"""
from __future__ import annotations

UI = {
    "overview": "Panoramica", "structure": "Struttura del repository", "dev": "Ambiente di sviluppo", "architecture": "Architettura",
    "related": "Progetti correlati", "community": "Documentazione e comunità", "author": "AUTORE", "license": "LICENZA",
    "honesty": "Controllo di onestà - cosa funziona oggi", "license_text": "GPL-3.0-or-later - vedi [LICENSE](LICENSE).",
    "family": "**A.R.M.O.R.** (Autonomous Radar & Multimodal Observation Range) è un sistema di sicurezza perimetrale fatto di repository indipendenti. Ognuno ha la propria versione, i propri test e il proprio README; ecco la famiglia:",
    "here": "questo repository",
    "docs_intro": "Dove leggere di più:",
    "doc_matrix": "Matrice delle capacità: cosa è provato e cosa no",
    "doc_catalog": "Catalogo dei progetti: versioni e dipendenze tra i repository",
    "doc_changelog": "Cronologia delle modifiche di questo repository",
    "doc_license": "Licenza (GPL-3.0-or-later)",
    "contact": "Domande, idee e segnalazioni: electrohobby3d@gmail.com",
}

RELATED = {
    "ARMOR-COMMON": "Contratti dei messaggi, validatori, vettori di conformità e tipi generati",
    "ARMOR-RADAR": "Firmware del nodo di campo per ESP32-S3 con tre radar e un proprio pannello web",
    "ARMOR-SOLAR": "Protocolli di inverter e batterie solari e messaggi di un nodo gateway",
    "ARMOR-SERVER": "Coordinatore centrale: telemetria, allarmi, dispositivi, letture solari e telecamere",
    "ARMOR-STUDIO": "Console web: telecamere, radar, allarmi, energia solare e progettista del sito 2D/3D",
    "ARMOR-ANDROID-CONTROL": "Client Android dell'operatore con radar 2D/3D in tempo reale",
    "ARMOR-SERVER-AI": "Politica di inferenza visiva che spiega le sue decisioni e non agisce mai",
    "ARMOR-VOICE-AI": "Intenti vocali offline con una conferma impossibile da falsificare",
    "ARMOR-HARDWARE": "Contenitori, elettronica e matrice di accettazione da banco",
    "ARMOR-DEVOPS": "Distribuzione, banco di prova CM5, backup e TLS",
    "ARMOR-SIMULATOR": "Simulatore di telemetria offline con guasti ripetibili",
    "ARMOR-DOCS": "Architettura, base di sicurezza e matrice delle capacità",
}

TEXT = {
    "ARMOR-SIMULATOR": {
        "tagline": "Simulatore di telemetria offline con guasti ripetibili",
        "honest": "Gli scenari, i guasti, l'invio a un server e i 24 test sono reali. La geometria è **illustrativa**, non un modello del vero radar LD2450, e nulla è stato confrontato con hardware reale.",
        "bullets": [
            "**Scenari:** `patrol`, `crossing`, `two-intruders` ed `empty`, su una geometria d'angolo a tre sensori, con un ciclo di luce giorno/notte o una notte fissa.",
            "**Guasti ripetibili:** un nodo muto, messaggi fuori ordine o duplicati, un nodo instabile e messaggi volutamente non validi (lux oltre il limite, campo sconosciuto, troppe tracce) per i test negativi.",
            "**Deterministico:** lo stesso seme stampa sempre le stesse righe; non viene inviato nulla senza `--server-url` e `--ingest-token`.",
            "**Verificato contro il contratto:** `--validate` fa passare ogni messaggio per ARMOR-COMMON prima di emetterlo.",
            "**Invio prudente:** si accetta solo un'origine http(s) semplice; un 4xx ferma l'esecuzione, un 5xx o un errore di rete viene ritentato.",
        ],
        "note": "Tutte le opzioni, gli scenari e i guasti: [uso](docs/USAGE.md).",
    },
    "ARMOR-SERVER-AI": {
        "tagline": "Politica di inferenza visiva: decide e spiega, senza mai agire",
        "honest": "Il livello decisionale è reale e testato (26 test). **Qui nulla fa ancora girare una telecamera, RTSP o TensorRT**: serve il Jetson, e non è provato.",
        "bullets": [
            "**Profilo giorno/notte con isteresi:** poca luce sotto i 30 lux, ritorno al giorno solo sopra i 60 lux e mai due volte entro 30 s, così il crepuscolo non lo fa oscillare.",
            "**Fusione spiegabile:** ogni rilevamento e le tracce radar danno una gravità (`ignore`, `review`, `high`) con i motivi. Una persona vista all'80 % o più **e** una traccia radar danno `high`; la poca luce abbassa solo la soglia di revisione; un rilevamento più vecchio di 10 s è ignorato.",
            "**Solo raccomandazioni:** una decisione porta sempre `authorizes_action = false`. Il server centrale autentica e autorizza ogni azione.",
            "**Motori verificati con checksum:** i motori TensorRT precompilati sono accettati solo se presenti, non vuoti e, con un `engines.json`, corrispondenti al loro SHA-256. Non si compila né si scarica nulla.",
            "**Worker JSONL:** risultati numerati e spiegati; una riga errata segnala il proprio numero e non ferma mai il flusso.",
        ],
        "note": "Vedi il [confine dell'inferenza](docs/INFERENCE_BOUNDARY.md).",
    },
    "ARMOR-VOICE-AI": {
        "tagline": "Intenti vocali offline con una conferma che chi chiama non può falsificare",
        "honest": "Le regole degli intenti, la conferma firmata e l'audit sono reali e testati (20 test). **Nessun motore di riconoscimento o sintesi vocale fa ancora parte di questo repository.**",
        "bullets": [
            "**Una lista chiusa:** `status`, `silence`, `arm` e `disarm`, in inglese e spagnolo, dopo aver normalizzato accenti, punteggiatura e formule di cortesia. Tutto il resto, o ciò che è ambiguo, non viene capito.",
            "**Una conferma emessa dal servizio:** `arm` e `disarm` restituiscono un token firmato al primo turno e sono accettati solo se un turno successivo lo rimanda per lo stesso intento entro 30 s. Non si può falsificare, reindirizzare, riutilizzare né sostituire con un semplice `confirmed: true` (rifiutato).",
            "**Decisioni, non audio:** con `--audit-file` ogni decisione registra l'intento, l'esito e uno SHA-256 della trascrizione, mai l'audio né le parole grezze.",
            "**Solo raccomandazioni:** un comando accettato viene passato ad ARMOR-SERVER, che lo autentica e lo autorizza comunque.",
        ],
        "note": "Vedi la [sicurezza vocale](docs/SAFETY.md).",
    },
    "ARMOR-SOLAR": {
        "tagline": "Monitoraggio di inverter e batterie solari: i protocolli seriali e i messaggi di un nodo gateway",
        "honest": "**Maturità: scaffolding.** La libreria di protocolli (100 controlli) decodifica gli inverter Voltronic / MPP Solar e la console Pylontech, cella per cella e con le capacità, da risposte tipiche scritte a mano. I messaggi che stampa sono validati da ARMOR-COMMON, letti da ARMOR-SERVER e mostrati nei menu Inverter e Batterie di Studio, tutto con letture generate. **Nessun inverter né batteria è stato collegato**, non c'è ancora il firmware del nodo e ANT-BMS non è decodificato perché il suo documento di protocollo non è nel progetto.",
        "bullets": [
            "**Inverter Voltronic / MPP Solar** (Axpert, PIP, InfiniSolar e cloni), RS232 a 2400 baud: i frame e il loro CRC, e le letture `QPIGS` (rete, uscita, batteria, FV, bit di stato), `QMOD` (modo), `QPIWS` (avvisi e guasti per nome) e `QPIRI` (valori nominali). Si possono costruire solo comandi di lettura: un'impostazione cambia come viene alimentata la casa.",
            "**Batterie Pylontech** (US2000, US3000, US5000): la tabella `pwr` della console (tensione, corrente, temperature e stato di carica di ogni modulo), `bat <n>` (tensione e temperatura di ogni cella) e `info <n>` (modello, capacità residua e totale, cicli), riassunte come un unico pacco con capacità ed energia totali, e il frame RS485 con i suoi due controlli. I formati sono scritti a memoria dalla console pubblica e possono variare tra i firmware.",
            "**I messaggi di un nodo gateway** (`armor/solar/<nodo>/<dispositivo>/state`, uno per inverter o pacco di batterie), definiti in ARMOR-COMMON con schemi e vettori di conformità, serializzati qui e verificati da uno script.",
            "**Il progetto del resto:** quale scheda (solo Wi-Fi o Ethernet con PoE), come cablare RS232 e RS485 in sicurezza (conversione di livello e isolamento) e l'ordine in cui sono stati costruiti i menu di Studio.",
            "**Non ancora:** ANT-BMS, il firmware del nodo e la scheda Android. Nulla è stato collegato a un dispositivo reale.",
        ],
        "note": "",
    },
    "ARMOR-RADAR": {
        "tagline": "Firmware del nodo di campo (Waveshare ESP32-S3-ETH, tre radar o sensori di presenza, Ethernet e Wi-Fi) con un proprio pannello web e il nucleo testato su computer",
        "honest": "**Maturità: scaffolding.** Il nucleo indipendente dall'hardware (797 controlli: i decodificatori dell'LD2450, dell'LD2461 e di quattro sensori di presenza, il canale di comando dell'LD2450, le impostazioni e i loro controlli, la tabella dei pin, utenti e sessioni, la logica dei pin associati, il piano di rete e il serializzatore dei messaggi, il cui output è accettato da ARMOR-COMMON) è testato su computer, il **pannello web** è stato provato in un vero browser contro un nodo finto e l'**immagine del firmware si compila** nel container ESP-IDF 5.4.2. **Non ha mai girato su una scheda**: nessun frame è stato catturato da un modulo reale, il codice di Ethernet, ponte Wi-Fi, sensore di luce e aggiornamento non è mai stato provato, il canale di comando dei radar non è verificato né sul documento del produttore né su un modulo, il certificato HTTPS del pannello è creato dal nodo stesso e mai provato in un vero browser, e i decodificatori dell'LD2461 e dei sensori di presenza corrispondono solo agli esempi dei loro manuali, senza un modulo reale.",
        "bullets": [
            "**Due nodi da 270 gradi:** ogni Waveshare ESP32-S3-ETH legge fino a tre radar LD2450 sulle sue tre UART, montati a 75 gradi l'uno dall'altro, via Ethernet cablata (W5500) con DHCP o indirizzo fisso, alimentato con PoE o USB. *Add a 270° node* di Studio crea i tre radar già associati al nodo.",
            "**Un pannello web su ogni nodo,** con l'aspetto di Studio e in sette lingue, incorporato nel firmware: panoramica, rete, Wi-Fi, broker, radar, pin, utenti, aggiornamento del firmware e registro. Un nodo senza utenti apre il Wi-Fi `ARMOR-SETUP-xxxxxx` e crea il suo primo amministratore con un codice di configurazione; le password sono PBKDF2 con sale, le sessioni sono token casuali e ogni impostazione è nella flash del nodo, quindi un'unica immagine serve tutti i nodi e nessuna password è compilata ([il pannello](docs/NODE_PANEL.md)).",
            "**Un solo Wi-Fi da più nodi:** ogni nodo può offrire un access point collegato alla sua porta Ethernet; con lo stesso nome e password e il canale in automatico (1, 6 o 11 secondo la MAC), telefoni e sensori Wi-Fi vedono una sola rete con un solo server DHCP. Non è una rete mesh radio: ogni nodo mantiene il suo cavo. Un nodo può invece unirsi al Wi-Fi di un router (con ricerca delle reti), e uno senza cavo può essere configurato via **Bluetooth** dall'app Android.",
            "**Pin per il server:** qualsiasi pin libero diventa un ingresso, un'uscita (con uno stato sicuro se il broker si perde), PWM o una lettura analogica, e appare come dispositivo del server: un relè o un contatto non richiede un nuovo firmware. I pin riservati della scheda non vengono mai offerti.",
            "**Aggiornamenti via radio (OTA) con ripristino** dal pannello (due slot sulla flash da 16 MB) e un **collegamento da Studio** al pannello di ogni nodo, dall'indirizzo che il nodo pubblica.",
            "**Il pannello in HTTPS:** il nodo crea il proprio certificato (autofirmato, conservato in flash) e serve il pannello sulla porta 443 oltre che sulla 80, o solo sulla 443; il cookie di sessione è marcato Secure e l'impronta del certificato viene mostrata per confrontarla con l'avviso del browser. **Identità di traccia stabili:** i bersagli di ogni frame sono associati a quelli seguiti prima, così una persona mantiene lo stesso id, un frame perso non fa sfarfallare e le posizioni sono un po' levigate.",
            "**Sei modelli di sensore, uno per porta:** una porta porta un LD2450 o un LD2461 (tracker che alimentano il perimetro, con il campo proprio del modello in Studio) o un sensore di presenza (LD2410, LD2412, LD2410S, MR24HPC1) che diventa un dispositivo del server e pubblica presenza e distanza. Si sceglie nel pannello; cos'è ciascuno, il suo protocollo e cosa non è stato verificato sono in `docs/SENSORS.md`.",
            "**Decodificatore, salute e configurazione dell'LD2450:** un framer che si risincronizza trova i frame in un flusso rumoroso; ogni frame da 30 byte dà fino a tre bersagli che diventano tracce del contratto; la console e il pannello dicono per radar se trasmette, tace o manda dati illeggibili. Il pannello può anche leggere la versione del modulo, scegliere uno o tre bersagli e impostare zone di rilevamento (un protocollo non verificato su un modulo).",
            "**Luce ambiente e messaggi esatti rispetto al contratto:** il VEML7700 con range automatico; JSON di telemetria, salute e informazioni che segue gli schemi pubblicati e rifiuta di scrivere qualsiasi cosa non valida, con timestamp di orologio reale (SNTP) e un last will MQTT. La telemetria è trattenuta finché nessun radar trasmette, mai un «tutto tranquillo» vuoto.",
            "**Un'immagine per tutte le schede, come un prodotto di rete:** il firmware è lo stesso e la MAC distingue le schede (`armor-` e sei cifre finché non ricevono un nome); `adopt_node.py` dà a un nodo appena flashato il suo amministratore, la sua identità di broker e le impostazioni comuni della flotta via rete, con un codice di configurazione calcolato dalla sua MAC: 5 nodi o 27 sono lo stesso lavoro. **Strumenti da banco:** flash via USB-C, un nodo finto per lavorare sul pannello e un convertitore da un registro di frame grezzi a un fixture di test ([messa in servizio da banco](docs/BENCH_BRINGUP.md)).",
        ],
        "note": "I test su computer richiedono un compilatore C++17 (Linux, WSL, MSYS2). Vedi la [messa in servizio da banco](docs/BENCH_BRINGUP.md), il [pannello](docs/NODE_PANEL.md) e il [confine hardware](docs/HARDWARE_BOUNDARY.md).",
    },
    "ARMOR-ANDROID-CONTROL": {
        "tagline": "Client mobile dell'operatore per ARMOR-SERVER",
        "honest": "Le regole di sicurezza degli indirizzi e di decisione degli allarmi hanno test unitari (48) e l'app si compila. **Non è stata eseguita su un telefono contro il server**, quindi il flusso di permesso delle notifiche e il servizio in background non sono verificati. Armo, allarmi e dispositivi seguono le rotte del server ma non sono stati provati su un telefono reale.",
        "bullets": [
            "**Accesso con le credenziali del server:** IP, porta, utente e password; la password crea una sessione HttpOnly e non viene mai salvata sul telefono.",
            "**Monitor delle telecamere:** da 1 a 16 riquadri, una vista ingrandita, MJPEG dal vivo che mantiene le proporzioni, un joystick PTZ limitato, istantanee e registrazioni.",
            "**Inserire e disinserire,** dopo una conferma; **allarmi** da riconoscere, con un badge per quelli in attesa; **dispositivi** (fumo, gas, allagamento, porta, finestra, movimento, clima, prese, luci, sirene, serrature) con il loro stato e On / Off / Inverti.",
            "**Radar dal vivo, in 2D e 3D:** la scheda Radar disegna il sito come progettato in Studio (terreno, edifici, alberi, pali, campi dei radar e delle telecamere) e le persone che i radar vedono muoversi, aggiornato ogni secondo e mezzo; trascina, pizzica e ruota la vista 3D. Il posizionamento segue le regole di Studio, ma non ha mai mostrato un radar reale.",
            "**Configurare un nodo di campo via Bluetooth** (dalla schermata di accesso o da *Más > Configurar un nodo*): trova i nodi che annunciano `ARMOR-xxxxxx`, crea l'amministratore di uno nuovo o accede, cerca reti Wi-Fi e imposta il nome del nodo, il Wi-Fi di un router o un indirizzo fisso e il broker, per i nodi senza cavo Ethernet. Compilato e testato in unità, mai eseguito contro un nodo né un telefono.",
            "**Libreria delle prove,** stato del perimetro e dei nodi, e **cronologia** di ogni avviso, nodo, telecamera, dispositivo, allarme e cambio di modo.",
            "**Notifiche di allarme** per un nodo che raggiunge HIGH, una telecamera che non risponde più, un allarme di dispositivo (fumo, gas, allagamento, panico sempre; una porta, finestra o un sensore di movimento a sistema inserito) e, a sistema inserito, un nodo che va offline; un controllo opzionale in background usa la sessione corrente e lo dice quando finisce.",
            "**Attenzione con la password:** l'HTTP semplice è ammesso solo verso un *letterale* IPv4 di rete privata o loopback. Un nome host che inizia soltanto come un indirizzo privato (`10.attacker.example`) o un indirizzo con uno zero iniziale (alcuni resolver leggono `010.0.0.1` come il pubblico `8.0.0.1`) viene rifiutato.",
            "**Un aspetto fatto di icone:** superfici quasi nere, accento ciano, ambra per l'attenzione, icone grandi con poche parole, barra inferiore, una pagina Informazioni e un pulsante di uscita.",
        ],
        "note": "L'APK di debug non è firmato per la distribuzione. Vedi il [confine del client](docs/CLIENT_BOUNDARY.md).",
    },
    "ARMOR-HARDWARE": {
        "tagline": "Contenitori, elettronica e matrice di accettazione da banco",
        "honest": "Il contenitore è un **punto di partenza meccanico stampabile, non una certificazione IP, RF o termica.** Nulla è stato misurato su un prototipo; ogni riga della [matrice di accettazione da banco](docs/BENCH_ACCEPTANCE.md) è *non testata*.",
        "bullets": [
            "**Il vero progetto è `CAD/CARCASA_SENSORES.scad`** (con esportazioni STL, 3MF e AMF): una base d'angolo a 90 gradi con visiera, tetto e fondo, gradini di ritegno, un coperchio frontale scorrevole da 2 mm e alette laterali, tutto guidato da parametri con nome. `scad/node_enclosure.scad` è solo una scatola provvisoria.",
            "**Volumi riservati** per tre moduli radar, la scheda ESP32-S3-ETH-PoE, la finestra del sensore, un passacavo, la magnetica PoE e il riscaldatore PTC. Nessun materiale metallico, conduttivo o caricato di carbonio davanti a un'apertura a 24 GHz senza attenuazione misurata.",
            "**Matrice di accettazione da banco:** i controlli di radio, ambiente, alimentazione, rete e telecamera, ciascuno con un metodo e un criterio di superamento proposto, e una tabella di compatibilità delle telecamere da compilare.",
            "Prima della fabbricazione, registrare i contorni esatti delle schede, i connettori, la posizione delle viti, le aree di esclusione delle antenne, il percorso termico e l'obiettivo di tenuta ([dati di progetto](docs/DESIGN_INPUTS.md)).",
        ],
        "note": "Vedi il [confine di validazione](docs/VALIDATION.md). La licenza hardware prevista è CERN-OHL-S-2.0; aggiungi il testo completo prima di pubblicare i progetti.",
    },
    "ARMOR-DEVOPS": {
        "tagline": "Topologia di distribuzione e banco di prova CM5 isolato",
        "honest": "L'installatore del banco CM5 è stato eseguito su una vera CM5 che ospita altro software, rimasto in salute. La topologia Docker Compose e il suo profilo TLS opzionale sono stati costruiti ed eseguiti davvero con Docker Engine in WSL (`scripts/test_compose.sh`, 12 controlli, che hanno trovato e corretto tre difetti), ma **non sul Jetson**. Gli script di backup e ripristino hanno un test di andata e ritorno superato.",
        "bullets": [
            "**Banco di prova CM5:** `scripts/deploy_cm5.sh` costruisce in una copia pulita, invia un archivio ed esegue `scripts/install_cm5.sh`, che crea un proprio utente, una propria cartella e due unità systemd su porte proprie (tre con `--with-mqtt`: il Mosquitto proprio di A.R.M.O.R. sulla porta 18883, verificato su una vera CM5), con limiti di risorse, e non tocca mai un altro progetto ([dettagli](docs/CM5_TEST_BENCH.md)).",
            "**Topologia Compose:** un broker Mosquitto non anonimo con un'identità per nodo, il server e Studio dietro un nginx che inoltra `/api/`; solo Studio è pubblicato, sul loopback. Container rinforzati, una rete interna per il nucleo e volumi con nome per lo stato.",
            "**Dispositivi e letture sul broker del banco:** il server può ascoltare e comandare `armor/device/#` e leggere `armor/node/+/info` e `armor/solar/#`; `scripts/mqtt_identity.sh add device NAME` dà a un dispositivo i propri topic e `add bridge NAME` a un bridge Zigbee2MQTT o Shelly tutti.",
            "**Segreti:** `scripts/generate_secrets.sh` crea segreti casuali senza stamparne nessuno; `scripts/check-required-env.sh` rifiuta valori mancanti, di esempio, corti o ripetuti.",
            "**Backup e ripristino:** `scripts/backup_data.sh` crea un archivio cifrato AES-256, verificato e con checksum dei dati del server (senza le prove salvo richiesta); `scripts/restore_data.sh` lo elenca o lo ripristina senza mai sovrascrivere dati esistenti. La chiave delle telecamere volutamente **non** è nell'archivio.",
            "**TLS:** un profilo Compose `tls` opzionale mette Caddy, con una propria autorità di certificazione locale, davanti a Studio ([dettagli](docs/BACKUP_AND_TLS.md)).",
        ],
        "note": "Vedi il [confine di distribuzione](docs/DEPLOYMENT_BOUNDARY.md).",
    },
    "ARMOR-SERVER": {
        "tagline": "Coordinatore centrale di sicurezza: ingresso della telemetria, allarmi, dispositivi, letture solari e gateway delle telecamere",
        "honest": "Ogni rotta, sessione, cifratura e regola delle prove qui sotto è reale e coperta da test (`npm test`, 159 test, con una suite di integrazione HTTP completa contro un server isolato). Ha funzionato con un vero broker MQTT sulla CM5 (con script, non con il firmware di un nodo di campo), ha trasmesso video dal vivo, salvato un'istantanea e registrato da cinque vere telecamere IP tramite FFmpeg. Ciò che **non è ancora provato**: ONVIF con una vera telecamera ONVIF, il PTZ su ogni firmware di telecamera (funziona sull'unità Hi3510), qualunque hardware Jetson e le rotte solari con un vero nodo gateway (sono testate con letture generate).",
        "intro": "**ARMOR-SERVER** è il centro di fiducia di A.R.M.O.R. I nodi di campo pubblicano osservazioni di radar, luce e salute; questo servizio le valida, conserva l'ultimo stato noto di ogni nodo e lo serve alla console Studio e al client Android. Possiede anche tutto ciò che tocca una telecamera, così **nessun browser né telefono detiene mai una password di telecamera o un indirizzo RTSP**.",
        "bullets": [
            "**Ingresso validato:** le osservazioni HTTP e MQTT sono controllate al confine (identificatore, timestamp, intervallo di lux, al massimo 15 tracce) prima di raggiungere la proiezione di stato.",
            "**Stato onesto dei nodi:** un nodo che smette di parlare è mostrato come *obsoleto* e poi *offline* dopo una finestra configurabile, mai online su dati vecchi. Disinserire cancella subito un avviso alto.",
            "**Gateway delle telecamere:** cassaforte di telecamere cifrata, PTZ ONVIF / Hi3510 / PSIA, scoperta dei percorsi RTSP, un relay FFmpeg condiviso per telecamera, istantanee e registrazione MP4, e un watchdog che trasforma una telecamera muta in un evento e, a sistema inserito, in un allarme.",
            "**Libreria delle prove:** conservazione per età e dimensione partendo dalle più vecchie, **prove protette** mai eliminate e uno SHA-256 per la catena di custodia. Una riga di audit per ogni azione rilevante per la sicurezza, senza credenziali.",
            "**Stato che sopravvive:** la modalità di sicurezza e l'ultima osservazione di ogni nodo sono ripristinate dopo un riavvio (un riavvio non disinserisce mai il perimetro in silenzio). Ogni cambio di livello di avviso, di stato del nodo e di modalità resta in una cronologia degli eventi.",
            "**Uscita di allarme:** gli avvisi alti e, a sistema inserito, i nodi muti o offline vanno a MQTT `armor/server/alert` e a un webhook opzionale firmato HMAC; il tempo di permanenza prima di HIGH e le zone ignorate si regolano da Studio.",
            "**Utenti:** nomi e password (hash scrypt), un ruolo `admin` che gestisce gli utenti e un ruolo `operator` che opera; cambiare una password o un ruolo chiude le altre sessioni di quell'utente.",
            "**Dispositivi, allarmi e automazioni:** dispositivi di fumo, gas, allagamento, porta, finestra, movimento, clima, presa, luce, sirena e serratura via MQTT o invio autenticato, con stato normalizzato, disponibilità e comandi; allarmi con ciclo generato / riconosciuto / cancellato; regole che comandano dispositivi quando succede qualcosa; inserire e disinserire da una sessione aperta; e il progetto del sito conservato sul server per tutti i client.",
            "**Letture solari:** inverter e pacchi di batterie (con ogni cella e le capacità) arrivano via HTTP o MQTT, sono validati dal contratto condiviso, conservati con una cronologia (un campione ogni 30 s per un giorno) e totali, segnati come obsoleti dopo due minuti, e generano quattro allarmi (guasto dell'inverter, batteria scarica, allarme della batteria, dispositivo muto).",
        ],
        "sections": [
            {"title": "Modello di sicurezza", "bullets": [
                "Quattro segreti separati: **ingestione** (invio di telemetria, salute e letture solari), **controllo** (inserire / disinserire, eventi), **operatore** (automazione) e **accesso a Studio**; ciascuno è confrontato a tempo costante e nessuno sostituisce un altro.",
                "Ogni rotta che configura, muove, cattura, registra, protegge o elimina richiede un operatore. Il video dal vivo richiede un operatore o un ticket di flusso di breve durata legato a una telecamera.",
                "Le password delle telecamere vivono solo in `data/cameras.json`, cifrate con AES-256-GCM, e nessuna API le restituisce; gli indirizzi ONVIF devono restare sull'host della telecamera e i reindirizzamenti sono rifiutati.",
                "Le sessioni di Studio sono HttpOnly e SameSite=Strict per 8 ore, l'accesso ha un limite di frequenza e gli errori non portano mai una traccia dello stack.",
                "Il server ascolta su 127.0.0.1 a meno che `ARMOR_HOST` sia impostato di proposito, e allora una password di Studio più corta di 12 caratteri è rifiutata.",
            ]},
            {"title": "API", "bullets": [
                "Pubblica: `GET /healthz`. Per un operatore: stato, informazioni, telecamere, media, cronologia, regole, dispositivi, allarmi, automazioni, progetto del sito e `GET /api/v1/solar` con la sua cronologia.",
                "Per i nodi di campo e i gateway: `POST /api/v1/telemetry`, `/health` e `/solar` con il token di ingestione, e i topic MQTT `armor/node/#` e `armor/solar/#`. Gli eventi raggiungono le console dal WebSocket `/api/v1/events`.",
                "Ogni rotta, la sua regola di accesso e il suo schema sono nel file OpenAPI di [ARMOR-COMMON](../ARMOR-COMMON), e un test verifica che non ne manchi nessuna.",
            ]},
            {"title": "Configurazione", "bullets": [
                "Copia `.env.example` in `.env` (ignorato da Git), oppure lascia che `run.bat` / `run.sh` generi segreti casuali alla prima esecuzione.",
                "Obbligatorie: `ARMOR_INGEST_TOKEN` e `ARMOR_CONTROL_TOKEN` (24 caratteri o più, tutte diverse) e `ARMOR_STUDIO_USERNAME` / `ARMOR_STUDIO_PASSWORD` (il primo amministratore).",
                "Comuni: `ARMOR_HOST` / `ARMOR_PORT`, `ARMOR_DATA_DIR`, `ARMOR_FFMPEG_PATH` (video dal vivo e cattura), `ARMOR_MQTT_URL`, `ARMOR_STUDIO_ORIGIN`, `ARMOR_NODE_STALE_AFTER_S`, `ARMOR_CAMERA_CHECK_S`, `ARMOR_ALERT_DWELL_MS`, `ARMOR_ALERT_WEBHOOK_URL` e `ARMOR_COOKIE_SECURE` (a `1` dietro TLS).",
            ]},
        ],
        "note": "Per installare sul banco di prova CM5 (isolato da ogni altro progetto, con utente e porte proprie) vedi [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-STUDIO": {
        "tagline": "Console di esercizio e progettazione: telecamere, radar, allarmi, energia solare, prove e planimetria del sito",
        "honest": "Studio dialoga con [ARMOR-SERVER](../ARMOR-SERVER) ed è coperto da 176 test unitari (lettura delle impostazioni, unione delle telecamere, aritmetica dei grafici solari, ogni menu mostrato nelle sette lingue, host statico). **Non** sono provati: il video dal vivo e il PTZ con ogni telecamera reale, i menu solari con un vero inverter o batteria, né una revisione formale di accessibilità o usabilità. Finché il server non è raggiungibile, Studio mostra dati dimostrativi e lo dice nella barra superiore.",
        "intro": "**ARMOR-STUDIO** è la console dell'operatore. Non detiene mai una password di telecamera, un indirizzo RTSP o un token: accede al server con nome utente e password, riceve una sessione **HttpOnly** di 8 ore e tutto ciò che è privilegiato passa da quella sessione.",
        "bullets": [
            "**Monitor delle telecamere:** 1, 2, 4, 6, 8, 9, 12 o 16 riquadri che si adattano alla cornice (16:9, tutta la matrice visibile, senza ritagli), una vista ingrandita con joystick PTZ limitato, istantanea e registrazione MP4; una **libreria delle registrazioni** per filtrare, visualizzare, riprodurre, proteggere ed eliminare le prove.",
            "**Allarmi, dispositivi e automazioni:** ciò che richiede una persona adesso con riconoscimento e registro chiuso; dispositivi di fumo, gas, allagamento, porta, finestra, movimento, clima, presa, luce, sirena e serratura via Wi-Fi, Zigbee, Bluetooth o cavo (preimpostazioni per Zigbee2MQTT, Tasmota e Shelly); regole che comandano dispositivi quando succede qualcosa; un grande pulsante inserisci / disinserisci.",
            "**Energia solare:** il menu *Inverter* disegna la casa come un flusso di energia animato (pannelli, rete, inverter, batteria e carico, con trattini più veloci quanta più potenza c'è), indicatori, letture, avvisi in parole e grafici di storico; il menu *Batterie* mostra ogni pacco con un livello di liquido, le sue **capacità** (residua e totale, Ah e kWh, cicli, modello), ogni modulo e **ogni cella** come barra con la sua tensione e la differenza in millivolt, e grafici di carica, tensione, corrente, intervallo delle celle e temperatura.",
            "**Panoramica e sistema:** lo stato del perimetro, un riquadro per parte, una mappa viva del progetto con ogni dispositivo e una pagina di sistema con la traccia di audit per un amministratore.",
            "**Radar:** una mappa dal vivo disegnata dal tuo progetto del sito (terreno, edifici, telecamere, radar e loro copertura) con i bersagli che ogni radar segnala, il loro percorso recente e le zone ignorate; stato dei nodi dal vivo, con i nodi muti mostrati come *obsoleti*; il pannello proprio di ogni nodo è a un clic.",
            "**Progettista del sito:** disegna il terreno (rettangolo o qualsiasi forma, con lunghezze digitate), posiziona edifici di più piani con cinque tipi di tetto, porte e finestre a qualsiasi piano e altezza, lampioni, camini, pannelli solari, antenne, pilastri, pali, strade e sentieri, poi telecamere e radar dove vuoi; una pianta 2D in stile CAD e una vista 3D che puoi orbitare, tagliare piano per piano e modificare; annulla e ripeti.",
            "**Configurazione:** indirizzo del server, telecamere (ONVIF/RTSP), scoperta, utenti (il tuo account e, per un amministratore, l'elenco di utenti, ruoli e password), tema e lingua; un'esportazione portatile del sito **senza credenziali**.",
            "**Sette lingue** (inglese, spagnolo, tedesco, francese, italiano, giapponese, cinese) e undici temi, quello predefinito chiamato *Armor*.",
        ],
        "sections": [
            {"title": "Modello di sicurezza", "bullets": [
                "**Nessun segreto nel browser.** Le password delle telecamere si digitano una volta, si inviano al server e poi si vedono solo come stato «salvata» mascherato. Le esportazioni del sito omettono nomi utente e indicatori di credenziali.",
                "**Le impostazioni salvate sono input non attendibile.** Sono lette valore per valore: un'origine, un tema, una lingua o una forma non validi vengono scartati, le posizioni limitate e le liste contenute.",
                "**Nessuna richiesta a terzi.** I caratteri sono locali; l'host statico invia `Content-Security-Policy: default-src 'self'` limitata al server configurato, `frame-ancestors 'none'`, `nosniff` e `no-referrer`.",
                "Il video dal vivo si mostra solo tramite un indirizzo di flusso che il server rilascia a un operatore.",
            ]},
        ],
        "note": "`tools/serve.mjs` legge `ARMOR_STUDIO_HOST` (predefinito `127.0.0.1`), `ARMOR_STUDIO_PORT` (`5178`), `ARMOR_STUDIO_DIST` e `ARMOR_SERVER_ORIGIN`. Per installare tutto lo stack sul banco di prova CM5 vedi [ARMOR-DEVOPS](../ARMOR-DEVOPS).",
    },
    "ARMOR-COMMON": {
        "tagline": "Contratti dei messaggi, validazione e lanciatore di progetti condiviso",
        "honest": "Gli schemi, il validatore Python, i 142 vettori di conformità condivisi, i tipi TypeScript e Kotlin generati e il lanciatore di progetti condiviso sono reali e testati (19 test). Il file Kotlin è generato ma **non ancora usato** da ARMOR-ANDROID-CONTROL, e il comando `set_thresholds` porta un solo campo `sensitivity` perché i veri parametri del radar non sono definiti finché non esiste il firmware.",
        "intro": "**ARMOR-COMMON** possiede il significato di ogni messaggio di A.R.M.O.R. I nodi radar, i nodi gateway solari e il simulatore producono questi messaggi; il server, l'IA visiva e il servizio vocale li consumano. Se due progetti non concordano su un campo, decide questo repository.",
        "bullets": [
            "**Un'unica fonte di verità:** schemi JSON in `src/armor_common/schemas/` per telemetria, salute, comando, informazioni del nodo e i due messaggi solari (inverter, batteria con celle e capacità). I campi sconosciuti sono rifiutati ovunque.",
            "**Un validatore che non può saltare una regola:** interpreta direttamente lo schema e rifiuta uno schema che usa una parola chiave che non implementa.",
            "**Vettori di conformità:** 142 payload accettati e rifiutati eseguiti da ogni implementazione (Python qui, TypeScript in ARMOR-SERVER, i controlli di ARMOR-SOLAR), così una deriva fa fallire la compilazione.",
            "**Client generati:** i tipi TypeScript e Kotlin nascono dagli schemi (`tools/generate_types.py --check` li mantiene aggiornati).",
            "**Contratto HTTP:** `openapi/armor-server-0.1.9.yaml` descrive ogni rotta del server, la sua regola di accesso e il suo schema.",
            "**Lanciatore condiviso:** `tools/armor_project_tool.py` dà a ogni repository della famiglia lo stesso flusso `build`, `build-test` e `run`.",
        ],
        "sections": [],
        "note": "Topic del broker: `armor/node/{node_id}/telemetry | health | command | info` e `armor/solar/{node_id}/{device}/state`. Vedi la [guida ai contratti](docs/CONTRACTS.md). Il lanciatore condiviso crea un `.env` ignorato alla prima esecuzione di ARMOR-SERVER con segreti casuali e una password di amministratore casuale; nulla viene stampato né versionato.",
    },
    "ARMOR-DOCS": {
        "tagline": "Architettura canonica, base di sicurezza e la verità su ciò che è provato",
        "honest": "Questo repository documenta interfacce e procedure che sono state validate, e dice chiaramente ciò che non lo è. Leggi la [matrice delle capacità](docs/CAPABILITY_MATRIX.md) prima di credere che una funzione sia «finita»: indica per ognuna se è stata solo simulata, testata su computer o verificata su hardware reale.",
        "intro": "",
        "bullets": [
            "[Matrice delle capacità](docs/CAPABILITY_MATRIX.md): per ogni capacità, simulata, locale o verificata su hardware?",
            "[Architettura](docs/ARCHITECTURE.md): reti, confini di fiducia, tempo e ordine.",
            "[Base di sicurezza](docs/SECURITY_BASELINE.md): il progetto delle VLAN, ciò che il codice impone e ciò che manca ancora.",
            "[Catalogo dei progetti](docs/PROJECT_CATALOG.md): i dodici repository, le loro versioni e le dipendenze.",
            "[Interfacce](docs/INTERFACES.md): chi produce e consuma ogni interfaccia e dove ci si fida.",
            "[Prima fetta verticale](docs/FIRST_VERTICAL_SLICE.md): cosa dimostra il test dal simulatore alla console e cosa no.",
            "**Strumenti:** `make_readmes.py` scrive il README di ogni repository in sette lingue, `make_brand.py` il suo banner e la sua icona, `publication_check.py` cerca qualsiasi cosa privata prima di una pubblicazione e `clean_history.py` crea una copia pubblicabile di un repository.",
        ],
        "sections": [],
        "note": "Gli audit della famiglia (in spagnolo) si trovano nella radice di questo repository.",
    },
}
